apiVersion: ENC[AES256_GCM,data:OvU=,iv:trHptGZkUhDe8ZeTNGLLqVsJfXmGNX8MWhXA9QmqhqI=,tag:UECPBdzDE5Gwovmh6RAlfA==,type:str]
kind: ENC[AES256_GCM,data:u6f3bFqO,iv:vuPfa7kej+tVPwZ7pX85fPnVybX41y55PLaFTKc1cjg=,tag:8vG4jvN2gJEEsPpIjmTBNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/p9FPzhuENg8ZbTIXbSZniYa,iv:iDkO8tI7Y6MigUO18g9lAR+OvIax6FKijWUhQLRQmr8=,tag:ahULOQHIpyP7M1ecOk/e9Q==,type:str]
    namespace: ENC[AES256_GCM,data:pcTaFg==,iv:DtI3EXA9BxudNjCC6H8DluxZ42NWxMUSktGwmmmTOD4=,tag:sCLb9/jXJJmTFPAAOjtItg==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:+iJ682/IK6X2lNIqVt63tCC0pk4gxdkrqwXpzcGMLc851Rn7R2zD3UJD,iv:6BQG6uqiidI9tUA9h+PzdOD9hTi5qaNsuLDABl8brek=,tag:uCkrTENxtfu1CPtsZgXXvQ==,type:str]
    admin-token: ENC[AES256_GCM,data:ZYcTg8h1no0SzksWGZRsnteh0VUm2kbQSZw5YxufQkzpEZjZcf8JGn2KvVAhwXauhX4vySr/9Gj4VfDvjQ==,iv:FaDPkHczRRwd9V3pmS+VqteP3/dTDj4/XCRwg20DR9A=,tag:E36bscfmNWDMiyMn9hJ7cg==,type:str]
    smtp-password: ENC[AES256_GCM,data:EWZ+jOypEKraIa4L4B9YJyVPrmSmbSOgjSKCsxkI+jnNmkOR,iv:dQFXajK5F2Jju7hAaDMRLM73/ICvUECXbLrP2wfZQu4=,tag:qgJYE4ZxLVGowWnSIDM1Aw==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVg4cnMxb20zdmhXcTli
            QjNyWkEvMys3ckJnRVhlZU9kVEtCTGdacmx3CjhjcjV6VHFBYk10VG02bStRWVR5
            WUR3azh0VlF0clF6T1pydVhPZzlWWG8KLS0tIGMxK1k2VWx1c0tLZXFZajFKZ0la
            MkVRNEhHUHZNYVB2dSsrVGZha25jY2MKKFZ0na//fdFZgCVzZ9/296d1ablo9BQt
            /+hDD7Y+/d+rm05+LkzL5e8xibS7dRRVpSW/V8vqpHkvjvhQVN+v0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T10:42:33Z"
    mac: ENC[AES256_GCM,data:V4H/cRLpuwq1WlZiezrRPg1tgYkClMNwQ0vE4K1mXSO8Dqw7t+j1qx6k28S+u9KeUwWYmU4b61gVu8WAOQpqO+DIs7X0/5XPxdX7Yt7f6W0ODw/9Navoxx+fxBVAxhwigub5mGcUaFO7g4g3jq9OF179qmn8fToPXiSLK/J9yMI=,iv:QQWBrdafuEJwyOXzleTxE9itmpAnVqLQROCsWsVAfQk=,tag:ozcp99mPc5dw7rVWCiMtRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
