apiVersion: ENC[AES256_GCM,data:4F4=,iv:tD7X+rgpKDN+rzLrIAkvssdUJ8l3iyipHSNq694Z9yU=,tag:qOsKedKbMGGDga0u8xX7CA==,type:str]
data:
    access-key: ENC[AES256_GCM,data:yX8qgxqgHHiTIV1cR60B1s+vNZV+OA4S78ktBw==,iv:7WFDV59gqtNpWjGGck3xVStic1ph3k8gi3vpVN6x9fo=,tag:AsBQLVhEZRJKHdqtYC6xPw==,type:str]
    secret-key: ENC[AES256_GCM,data:ZMXhGUuD6egVkYZFqbQ/ooYHVi9ifqMDuZr+wVkvKCjgOhzFU3OXgphM9rYY7KXNL0uT9iSyQfs=,iv:2qhJHuHd9mgTUeMbr1l6LSjjwpqidN00+W0k+PNnG0k=,tag:F2yu7DyFtNYNPGeQJzUmXQ==,type:str]
kind: ENC[AES256_GCM,data:FP1Lvjk6,iv:rAaAEPTk9HITwBVy48QdxDdzjxnjSvGEyA3JBSvFUP0=,tag:09BaJEExNHz7zzDSrMd27Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1lKRaUa/O3fYKMR7Wq0Gv40ibZvB,iv:d2IvubmFWlJp2JxeozUV7jVKyoFHKIZ5yvNpb689zKA=,tag:mSlyjaq+DCTERKwOj/KiLw==,type:str]
    namespace: ENC[AES256_GCM,data:TREAdveW9p9j,iv:mOCbw30uWVGtfb5HTraPmfuNeGinCWMo41XY6afitT8=,tag:CdncHoKvV31yqJ+G/3WZPQ==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OEhzTDlJVFJhbVhhMnB6
            b3lqc08wTmFlWUFOUWlvU09Cd3dDU1IzdWpNClIzMFlBdTBiaTRUYjJiaDhVWU5h
            d3EvdURZSHdicE9oeWUxa1VvWTJRejQKLS0tIGVsSVc3N1o0bXpOcE1uUjRySEs4
            SVRjblQzSUJLSTBUZmhZTjRYK3Z0RWMKw6xq5QBd+3EYba3g2SXCqmBRRNivNZZq
            p1L1R09cJHzMlYCwBG20FTBiMNPwZt+dJUoakPFunrzV2x6UnJqQJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T17:09:33Z"
    mac: ENC[AES256_GCM,data:UoewiNjtTCwfnOqyUso4ngeZm1Op4XrC1Kwzr0cibwFcZC74OJ5Vk8tKyyeFH7S1dE4Zzh9fcqVZ2QwJKel3h8gLNyNUMPSBsCWn/GiXJ9IPW+gEZyO9sSqfaUzJK72/TXOUZ+zdHU6h/oxbJ45JcK8LaNjChtME5eowf/SgCFE=,iv:gW0VQZKdfIidjC13cjzxBZL9rl9AYcw0C3r7GX+Tatc=,tag:gFuMQJWNzIDA03xdCxOCGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
