apiVersion: v1
kind: Secret
metadata:
  name: db-backup-credentials
  namespace: databases
type: Opaque
stringData:
  access-key: REPLACE_WITH_MINIO_ACCESS_KEY
  secret-key: REPLACE_WITH_MINIO_SECRET_KEY
