apiVersion: ENC[AES256_GCM,data:2Z0=,iv:GN6aq0UkIwOotzUcuKONgAP4CG4wxPE4ves0o7abaGI=,tag:+xqtw8QqDJZzvq3maS6J3w==,type:str]
kind: ENC[AES256_GCM,data:eKDTZ9/9,iv:q7DA56ER+9TCR0FK4AUChv8pkSQePcT/igazL1tFen0=,tag:PatjSJbmjd1V7TmdIL4x4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i7xgfJkeXjSLzO5IzHgQ96kr6PbP,iv:+RZKQWggHjTBLEIdn0pjNKM3ugnanZBwoYKdPS0YciE=,tag:TaRB4gsKYDWIxQUCfKPD3Q==,type:str]
    namespace: ENC[AES256_GCM,data:x/hHPcYOstPs,iv:4D4weiyChCLWU/OkcNlpE7Mgq2o5vsMVEeZV8AZ8b90=,tag:X4/6b/sN9PzrLDdWxtEtjQ==,type:str]
type: ENC[AES256_GCM,data:z3ltnaMo,iv:PIwP8HgiqNupuhL7dZCiYEXwkX5kjqnFtOMc0591N+c=,tag:J1zW0y78Sg30jAdMVsCbBA==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:vr8sIuBhiBdoagpt0Xcm/2DWgqo=,iv:j6SF430nK+3gEuXNSaavFUlnFuOWW32mi46ilHayakI=,tag:CvFJGyoCSnB2YoNjFs7xMQ==,type:str]
    secret-key: ENC[AES256_GCM,data:F0SbrURlVfb4e16Fnpvi3BiVj2OmP6IXzH9Rz500B/4eg9uVnndQcA==,iv:2aoDpVvvo3pyoJKqLZtuMr/l9s/GT80UHVKbGY8HVZc=,tag:xHl41HjClc2SN0QtbIw/Ng==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUWxoSW5qcUhQemZHWGRL
            bmd4VjBsYzROTnpCZlhCNFBtV0VZZnVRZEhFCmxDbEZHYWVPeG9qajQrOFFJRGx5
            WGYxa0MxOVVSZjlrb2I3dGxmdkF4ZDAKLS0tIEdnVGRFaTRyYVV2a3ZhY3U3WHZk
            NGNnRDBNbDR0bXc2TjQyekFCVml3QjAKUTBemvXz7RPV125Mn4l6KD/TLGooL2oK
            mg1qsCI8YliuGgHrL9UQpo2ri88an7rnz4Rie25teM17+q7gdymWKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T15:00:02Z"
    mac: ENC[AES256_GCM,data:f4QlCqnrDY6/YEE5SyE2a8fUBN445A7rrsET4H0KDBUVl3aGdtPcSp88xj7kZekCyzr3sr63Bk+J6cLf2BXKLRit7Sl1TFEbYCnAhLBgycrBho3aOdh1om5kWOZemc6X15bJLB119VY9sLSKvNOeRvVGc2lM0A1KLfhLDrSebWY=,iv:pxJ4DQvk3aNM0yeaIt3+/gi6kulf0KrTmofzko5FV7c=,tag:5IARpeI8SWjHlbndfXS80g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
