apiVersion: ENC[AES256_GCM,data:vX4=,iv:Cf03+2HG1c5th4CqmO7GZAdWF6MP7zBmQe7nz6IssH0=,tag:LWM9+P4P2uc0nlIGsJu1gA==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:xrYhHwBjLOe8pit5YVMPlWbQcr1z2R5+NaO3j1NeBGb33U+PnaVuez9MOWyNts5Ajl/2AX/l2vypJ2E7,iv:J6lnM1teGzxLen4WPBsvXA5u8QEZAY9AqXpDEhfL60w=,tag:ub8A5sEcwkL1GLp/bNRobw==,type:str]
kind: ENC[AES256_GCM,data:5x4814VG,iv:93uNmnzsiL4IjPkchyoPRRre8k/MUhYafB/01yJJQQ0=,tag:yRDP/pIUSPvFZAnV4/Oqtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GMW0/KBgZBgOzgXK7FP3J6w=,iv:3xHjhY8fN7+hHmhejUN/etiyEz1nCWX1wlbFxY0kobE=,tag:+hx8BPZ/g2vrx+vGp/Kikw==,type:str]
    namespace: ENC[AES256_GCM,data:+byQQRb8E6MU,iv:mCoGumGpFvPDSWW99jmjpw0U1r3gGoZU2RwxPRexy6U=,tag:lO6t4PhQe5LXXEZJ9wjh9A==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbjZyZTFUbll0NHI2eFQ0
            eW0vNEh1MG1wbW1wZU9MTEpteTlrSWwxbUdJCm5Ga1lxSWJqbkhqbDlpR09BU2Zk
            RlZJM2FidUpHOVVRTzVtampiOStoS28KLS0tIGlnYTRQY3lxc1ZPOVlrUkpqZGNQ
            TVNNTXhNeU1pbU9KcHQrMDN3MElEWDAKfQzyMukUCtY2Q8xUU90oF1Txoyr24NLY
            WmFfCWdCRcivvAwDB6LWV0/OOcWjJkadLelGbCepReEu6MKLZRfV1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T21:59:17Z"
    mac: ENC[AES256_GCM,data:H3FLSS1xgwiGt5igZXWPf0VDYgcIJ5zq762R17L0TT6tm8+TNkpwXWCfYVcFBo45Mzs1GaHihc8KQvlzl+UcRrgCgvGlOv80yD2RZrcmbO/H97CgUtRLOxe5R9qrmqgHdfJDMQs9cG5gZDDtBfiZkvmS0PU+CzPMSB7KsAs7cwo=,iv:bn+Z+ljqYABBSTf6tV+2VzLRD7XBD/VJPQaYfSs29jM=,tag:BmCTa444RvvO5oysL7FttA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
