apiVersion: ENC[AES256_GCM,data:pAQ=,iv:mVtRfoWCaku36GbalRkWYbsYS0EA42Njssly1lr6THw=,tag:9mtGn+cnT1YRKxDsYNDuOQ==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:W7CiJ3cCe3w3KEW6BzeE95aR800uqI6/4+GAbSKytCs+cHk7LhOFCuK+2Fs=,iv:gKlCWMWPYB7yHkqIMd5UtpvL+uCro+HnhZpU/CoHdJI=,tag:ayf0+DkB2zwRNRfjzkRzOQ==,type:str]
kind: ENC[AES256_GCM,data:/If0NRng,iv:UnsuKF30w1skjwUx8bCagd0YdV6o/S2PPG0d/8ZUK6g=,tag:XQ51nm5oZvCyRl3ntaaSYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o2TIO5n3FLZCnohmA8GongU=,iv:cpgNlIqQjCfAQzIZGU7oqjC1m6WhyozzdTqoO2An+DM=,tag:VVOElYFEj/UNG0zQMN3aVg==,type:str]
    namespace: ENC[AES256_GCM,data:qvwujk6PCW24,iv:KgtEYUx/kVmeIAObE+VaOZkPsXAE/sotva57pBMFk3s=,tag:TA9lm1odOJo30trJw3hXTg==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWC9qOE96QkpCaGFDSkF0
            QnlnOWlJRjkzek1TRlFhVGNwSzRLR04yd3pZCmNZQTk5QjB2aVBqU2lCSEt5bVZq
            SEhVTlJXa2s4SjZDNGdkMm9ROERyRHcKLS0tIGFRazd5RVp4REI4MisxQU1udTNq
            L0FVMWwzSHpDTjFwVFZCNVJUcUJhZE0KUrcMIWDXscph0YQT3DGQbg0U5obNm6Ky
            fYPqA5dB4v6Gw69Dwn8FZO9MIVawPsAj60/fisU1Ogq2KgkmqXQUXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T17:09:04Z"
    mac: ENC[AES256_GCM,data:rq/O8K0PfNxFmc9EmHd5G4HD7GpF+8S4W4XnEj9EPim626QnlJoSrSLgTbLyCDt1zD4MlgV8LQx/SvPODpT8+cR2GSNViBZBqhsphOfagaed8Df3N+s5W0f2u4nAquxZEX5WavSt5XYJRsJ8sHkkm3nzxqdJGAFzrZaEJDgoIv0=,iv:/phEDJ1EOe0F/B8NO5pNTVSF6mTTSirD/Bsa2dT3v+s=,tag:J91eus46e2+Jjxm73M7FjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
