#ENC[AES256_GCM,data:XM1ZcVvMrc2H/7ya2OxQOxn37+GsEx/bmuKkLulQzmjbdF2MKDoaC1GvPQg0wg94TA8hOM4=,iv:giZUVOVxwk01svXmMW4cd94prrsfGosAFIoQHy7LJWQ=,tag:ke0ujOcNPvWmAWwdO9WUtA==,type:comment]
#ENC[AES256_GCM,data:pl4JyoHSUYnwDJcjg7D8oHsx6aOOOpPcpzQkedY3ndU3QHeo6suB8x5uMQwW2Xn/HjaF+WR1Qca452TSYrrhfPS/FG3/,iv:xDJ0KGr91i0/o8tcx9BSZEKTgCBEFT6AqwUHxzEsIgo=,tag:bzehUUlA80MTkVvbPNxfrQ==,type:comment]
#
#ENC[AES256_GCM,data:hpb6yCvhQm7qKzzeVCgVX6oGHetoWm4xu1G43u66jA==,iv:LOmgdXUDgaNIYwWHmuGmDxe5EM8vTH4schsPNL65mvE=,tag:di+IVoE287pHbVVy/qjfwQ==,type:comment]
#ENC[AES256_GCM,data:sopj+s7mFLz+2qYHDYdFXeJGBdaAlYEe9lZaEKLC1Un5dicjPXZ3hCPWixdB6EqQ,iv:UatSIcQeftA/HlM8aJXs8u78m0lw50/HtmFNu/B4Xh4=,tag:q3TftMscaPCacCtoYeizuA==,type:comment]
#ENC[AES256_GCM,data:LwPxbpr6v8bHv00IABlPQ5EcvZWIt3DTaabcdmY=,iv:f2nTiY0ptIA63htADBEFi2poxgLDRlT8/taGZ/xrhIs=,tag:1N7sQE5OnUwqvzPFiLLEiA==,type:comment]
#ENC[AES256_GCM,data:Hyen/BeJTaH2xFDBSdalVMVjBjUg5m/T9c1BUzQvkHdyNJdZ094=,iv:dRu5iplFVgcKLe7TgR6bV8ZbFHgnAF0/uGgr0X++xX8=,tag:Jtwv5F5AWKTy16uoNJYScQ==,type:comment]
#ENC[AES256_GCM,data:GkonsDbNEUiKcQc80ukNObNfsu/d8SLWfN7E9xIRORJMM4QlvxUIOLE9Fr0jPpBujEHYg4GYtMLOrY0jCDGQwAg=,iv:DnyKMjpFN43+8IqWLg8zeowye8TP5ylJLjEv4/iXclw=,tag:CYfH8bNROTXrjTUbl1oSsA==,type:comment]
#ENC[AES256_GCM,data:LcQ1uOH9qIkuWApC5iuxOK0a1uloCu1V6E0pacF7kMSCC2OBW0t8ZY1BCYR7zSV1rnrg2QP2s6xxXLLVvBIVL5K8CYi/Fm1gCpeOvMckKFThmaXAyp4tfhLcSqxHpHXY5Dm2riLYkpxGXNeyqjzkG1C/IJCFpNwXgoY=,iv:4rsHAV4R/gIgzL2tFGpMgdun30r4Al197+OKamyBeRY=,tag:p4dRjz76Y+0tSqCXCsfBew==,type:comment]
apiVersion: ENC[AES256_GCM,data:ut4=,iv:xt9086r7Shz6IBfeDiLF/mnPaVVx1YHJ49qvrcMamyM=,tag:sVR04xhj55YVp2PlT5dsSg==,type:str]
kind: ENC[AES256_GCM,data:zim9Hzdm,iv:RV0OLwi/OjbPhL82EZiy0jSw9PxAHJVQR+Ahoja8Yuc=,tag:hixAcNv41W597ZJ/kM2XSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zVbxK7eWyebr2kl4mQ==,iv:5FkkxR4phXaCU7prUeL/XOMHu6/VWrhIqkqgY16jx2w=,tag:QKSwdZtAy+SxgWq4Q/pjSw==,type:str]
    namespace: ENC[AES256_GCM,data:Q2Sa5wEXxZ6HXw==,iv:HLh37DGes4+Su6TdnjLmtD2K4cEBLbNiNdHVrOVqk5A=,tag:A2d9qscAbcs1EbCT0GCOvw==,type:str]
type: ENC[AES256_GCM,data:tMw0VmCD,iv:qYOUPXS1YZyu4BvzWguc4oU8jq9SqDc+gKWqxKGXqHM=,tag:XV5d4hdWtJ/UeE5vVsUj7Q==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:/Jv6s9E=,iv:WaH/5jsu0bgv7uZJlZ6YsjRiynKKuIyh2NoCXneqhIE=,tag:EthJE/Bm+QqdtddyW0YBRg==,type:str]
    admin-password: ENC[AES256_GCM,data:aMpufGQijAxPpQOlAehfM5247e8=,iv:IUnAU8cVEdZGKMMO00/eJB4LKY6BKmNVaGlCLiVpRCo=,tag:TEpyMGXMl0oJFDGD9Hu5Iw==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWnBQcEl5YWNIa0dPRXNh
            MCtrTFVwY3FIS1dNUk95ZFRzRnpKSUYwbG0wCml6UkdMb1A5WHZWb2FyMjJ5MTUw
            aVJkbGsyeDY5eC9PQlQ1bDNYaFZDT28KLS0tIFZ2OHppOXQ4ckdrZWFqbUxBS1Br
            b0d3cTloay9hdm5jbE5CZU9udE9yUjQK+Fh/ETghE3wOtH1hKmcNTmJyZOh3Nf0P
            C7P5xqqS9pHEM74ksjzbLbQqwHU0SwaTRemACX8Y/NLYhMbLyVi1dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T20:04:23Z"
    mac: ENC[AES256_GCM,data:Ita8I9k8oGlrkUrMwzolp2AwS0IPi2O4MdeB8CHfC2IlWsR3fM/5C+iJ65U4kK12CkfxK1Oi44eN2hsp5BmSGrnoCIFQvRZwIh6350E49rLsY6NbKq+ZbatEAJ8aqFOALOovkhwtFOyThYa7pkE7kzA0s3d5/R8lyZFCwntMIXQ=,iv:5FFaxEQpeMB+eFnMdgzZDs3Znehp2l0gI7dGViw7NfM=,tag:DiV1B3TbDPZXgZYGg5GpEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
