apiVersion: ENC[AES256_GCM,data:a24=,iv:JzNdW+irwIwLZAk6Rctl5fmx5njdjVzgwF7CNmPDF7g=,tag:di3RmPkXPl3Ptvxu1Z6tiQ==,type:str]
kind: ENC[AES256_GCM,data:+6D60fuo,iv:EzVpJD+7KaQBeAh0pvtzes9V0HfnQs1FbGdlwG9SAlQ=,tag:DbnPXFHn16MK1v7FRPgD8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:q4LwmSfHyzqo5xvlwXavZkUtiFu4gg==,iv:AtH+4HSYt5DFG+fGRPlfUYLgj6frhOisb+VBNiNOGQM=,tag:4OUTrq9DM/52JIJwxxbN+w==,type:str]
    namespace: ENC[AES256_GCM,data:x1aS0agXCTjy4g==,iv:p1VL0q5PkBGSMSSvPX+AwqybznPd/jOaaRl6XkVjMag=,tag:lIyRBUSqQbJImm+L79vPSQ==,type:str]
stringData:
    client-secret: ENC[AES256_GCM,data:yigke6ws8N40mwFYmKH49h5p0f7IkV8Hnq3l0NWOxoLByR3Ea9FWTRG8/RGYAyHS7euTCFKP63pOZ3dq+fqe0hjxfzRid0F8DgyfuCFayOJxgagt5qzOJwM4cGSFNz9Enxi3mIZFIJlMUmvxuu1dEVfJH75I/Y5aQ0yvNtJV1rI=,iv:WJlvUgGLWUp41QZp0MtgNp4smWkTZlJnOmpzdUkgNoM=,tag:qYhKFKrHpvgJ2xyQD5JPdg==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR2lsOHRtejNyNUpUamxu
            aDc4Wmp6RmMwVzJweHhxeUt3R2YxTFUrbVhFCkJIby94bmtuKzBsa2JIcW1OWU9r
            aU1vZlVLRkhIUkZFYnpZWnI1VzNQRWsKLS0tIHFpYWw4ZlNJN3A5VGswRlBoNG04
            N2tHRllVbUs2NGw1UjE4VmRJd2FtZzQKifxasAyVyK5BNz9UgU6BLFnwG1Qx0kbE
            jSpXgsLPsTlOEMnJkdJ22UQ35fvzfXcLLeOwNxPOAFfNfMa2rgD1EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T06:27:44Z"
    mac: ENC[AES256_GCM,data:w59q/jlW9Wb+LW95zYs+F1TarzRwySw6pNG388MyuFyUr1Sgk560mdRw4ZCkz0p3xKiEYnG7B6CDGpQww4muZTsxVBtDsxORUfElbLpE2YiiGhtaVlGYw/tknmVOeJuSd/WvQZNSlwwDza/2WBBFzi80xOvueWDZwwsiIyPUfCE=,iv:MIRtMnSShkyR9DKaWM9jnGtzrUHsi+CrqAMza9+0SAo=,tag:hh0Q6SWTWyTr/eCXNcEXbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
