apiVersion: ENC[AES256_GCM,data:CAs=,iv:rACJrO/fpW0f4kEi54CTWW++k9lYe/PX1Ox6d4RU8zU=,tag:YYTSnZPjWT/FITtWGvWAyQ==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:AFD1yt5q/pkCBykyfkZxEkgD8byXuRR5VnaD6L6KswGDyewLwsbjsOBqYdM=,iv:mdEM6OAS+hmXqs9jiYyieFLRIMs8rGjokJLrYfsLUtI=,tag:QD+4VUb19MSk+pYNojG6Lw==,type:str]
    admin-user: ENC[AES256_GCM,data:ug4SeNJNj48=,iv:VIYESf+yQQGNl6fdCu5iIw4X+YFGz5sn4Sx5MPWHb0g=,tag:hGkPwDIId68Zull46LN/Ww==,type:str]
kind: ENC[AES256_GCM,data:9M2piz5R,iv:8YNKSIeZpeK/n2wLONZxv9Rx3Ww7qtE3qHdly9ayv8Y=,tag:Duu1J+upt4PfZNW9HV0a9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yU0BJycBbFV/Pnsw8w==,iv:K9k0n+O22uI9LnRFUvE2T/VnPXebjamDzBbNGOb+6IY=,tag:w27h9kD3JXK7acKtcfZDaA==,type:str]
    namespace: ENC[AES256_GCM,data:iCXiD3EQ78ZUug==,iv:XWMooh1eWtPNsl90jduUx5u+d1t/Ub+Longb2SfM44Q=,tag:z4zAAsxFr4fCveFGyfqd5Q==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSUpJQ2ZhdjRjM2tOc3RD
            YVVpUkQyRThvdXJ5WU1jK1VpbFVzL1hGbkRNCllUQndFSUFnQVQvaXhKWThuK1o1
            UXY0Y1h6SkIyWkhHZVRjMC9Yb1VEemMKLS0tIE4vMnJmMHhsTTkrUkNmbFlWL0dT
            a2NpcWJXS3hEMnJacWRpMjZqTG5jZ28KxeeTxbydvYaKnheA/i5bX69YWcug6LXr
            Cp0eGXKdDueh9m3OCNe/pBfbAPM0yGIOR/DUUJYc9uMXBbN7NLSnVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:01:41Z"
    mac: ENC[AES256_GCM,data:GRrJOmdb861Y3fq534a4wxlNUl0XROT4oTxrfBaL7yykJVlDlzcJSe8WAL9crUzKelq7s1BqbT1IoofjvyaiziYZffRoKKNvAzsYJ/bRmqPKGJw7N6G0GLOEQuD1yytxWtkhg6D//tCIyCeG68Wn8L1RJvfpfp9uKqIiBIWcYI8=,iv:mt9LtTLEXDoO0e+4lNVr5BVL9oevorKF5rj1doUST+E=,tag:khiO0qRDsREVPsvsBcMgpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
