apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - middlewares.yaml
  - tls-store.yaml
  - tls-store-internal.yaml
  - wildcard-certificate.yaml
  - wildcard-certificate-local.yaml
  - ingressroute-dashboard.yaml
