apiVersion: ENC[AES256_GCM,data:9iI=,iv:OuWxO2O8JsTIZvqSSEVUVRgFbz8O16F/AkePQ7LMGvU=,tag:bESTBeMqVI2xhr0tgSh+fQ==,type:str]
kind: ENC[AES256_GCM,data:U28OUzjd,iv:05079n4A0sJCM7DVnlDkAV4PXa3P5SW24BNkz5/4NZk=,tag:oOtmmsgJu/oNVFztBwMXVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/ojh9QyakFemFQ==,iv:xqg3JCQekpH7FkTxgLAYl/xlyAH0UxpOamcFgKVCE9c=,tag:BwUM7TZ3KQWPcIuiQlWP/Q==,type:str]
    namespace: ENC[AES256_GCM,data:m7aMJw==,iv:qm7Y7IdRAto8oHmpMHV0J26IuH+QKDN3LBU5WR2JZLU=,tag:Xmgd66DB2ttJ7+2kOTZppA==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:SVGlEqqMf4QSF57oi38UyHIfQE3BCQ/UNxpgI98rDi8=,iv:2wGg/A9BeJE3oHIx/Bc+7bkTLasMSnS0/sq7ACurG8A=,tag:7IBjVewa+1mz1gFX6KKQJw==,type:str]
    redis-password: ENC[AES256_GCM,data:WZlzXtSEsJ4h2ztjzCAUm4GkUo9iAdbH5lOb4wPdAgY=,iv:W2fYUMPR2ptHrUOgpixCvdO3VafWSZCRN4Fqksjb4/w=,tag:5ronxWoWzcfH2W0zpttTog==,type:str]
    encryption-key: ENC[AES256_GCM,data:pifheplKxx3/fuZQMFE8iG0SWPTLRirQIikGkG4vloD1l1bPlxUR8WYhN2leJG/6,iv:BoTavN6PQ9QRU2Ot37QAnWhTO/9hk9WO74DrwaKJKaM=,tag:mq1KNfb5/how9R0RENm7WA==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFg4LzErSERyUTBySzhz
            RWRUanBqdmdwNThkTmdrVTdGNkI1WlQ5WUd3CnJMeUdqYmpES1dBcm51NzZNZWNR
            OFNlMDJ4UzV6ZXFhK1QxT3ZlNXZpNkEKLS0tIE9wRHFyWEdTd1pKdkE3RjFYbTB3
            YjZmRTQzWWkrRUpvNkRHTmlXRUhKK2cKkosZjLdXdeUtBmcVwUA62GzOkuadKSHL
            9xpgAuub5xH+zI7Yx0WsM+rgZLrZGPaHlPBh4hhM5TU/faIDt3PStQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T22:30:00Z"
    mac: ENC[AES256_GCM,data:RMn2VcE3D/YjLSxC1oQW34bSnxRf6x9KpBpKY+9JWY7kEkqFuWKNHHBj95xc91k1WbaEONrIRllCQ+E+Qn2LBWQMgNUjE3WDL0h+aB4j3OhCWpilYuKIyVkk/17pibH/NHHGMDfn5SBQT2pFtt5Gun4u6j0TohYRawwWj0melEQ=,iv:ieESItYB+A7i7WXv8sqMh+Y9E5REnuPfbZz+vJ9dpSg=,tag:EcbCCZHswLqtl0YmsSd7WA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
