apiVersion: ENC[AES256_GCM,data:9tk=,iv:sCEO70Bid002bIjZaLo2mahuPv0g4ODJXP0tG9X+BY8=,tag:HVlJHhskq7OkQAOA4AMWMw==,type:str]
kind: ENC[AES256_GCM,data:cwuIRDvg,iv:f8x5Q4tauPZxyFyGVHRZSNmjlbTGQnOXzeFGPYcMqEU=,tag:n89O3Z/rgQSAvaso6GmXnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aZW0GOdbSZ3v/w==,iv:rKu+zh8ozB0srXVn2/VvTg/e45vHypV2wlChYBUCn1k=,tag:kuK+Q/NhJf8s+tTwsbU7oA==,type:str]
    namespace: ENC[AES256_GCM,data:LGjOfA==,iv:WpCZWYFL8kGHBtA0xC3myoXblPDYOlRBW4/j5y4Z3+o=,tag:5A4g8eP3056pBqy0ZyIgAw==,type:str]
type: ENC[AES256_GCM,data:3hEVtOME,iv:CWdwOpyCl0FTNNJDPxtSoc/IhEDf135t8l1TwfD+BhE=,tag:6lcA7CB/y5aD1zUMuBdv+w==,type:str]
stringData:
    #ENC[AES256_GCM,data:Mx+LncB+I1HwNRPkIt/iSZrnToX/4BSunh6nk0xqjJZbDuBhPfxcaw==,iv:+MdfhTlNLcY+OLFR+C+xZlVHRCV0bGLJ1cGin2KKnEA=,tag:NsMQnhPDU3rirZTFlYApqQ==,type:comment]
    #ENC[AES256_GCM,data:ZaOc3gliUDv2vgGUlCOHM3+BMw0RQHRcdUGZv8C3e5bEEn4vf/1bUOFO0ILXroqS,iv:T+4FFFiOhq03S5nihY5C6AkxW+xYVe7hI1P3wXM9CVE=,tag:0li3UL47h34G9IKridX2gg==,type:comment]
    #ENC[AES256_GCM,data:/xy48GELGItsVNnv5bf4SQIjNVCyiLt44uN2R/S4wF5wXIM/QqSbU7JvW7yU61QbsBsdaPcNhbBGOPCE4GbKu4TpO/pxaHBdAlivrAqF+6Hxp6DXNMETjdq/GqT/f6pHSTj/pdmcqnZB7AjcY9Kf9Md4qg==,iv:zE35mXxrknIUPc/HWnLrjdcl7f8YkKj47AB5MiCjgM0=,tag:zpLIoidmj6VCOBXiNQ2KNA==,type:comment]
    #ENC[AES256_GCM,data:EL4GzqwcpaxLmy3xbsffci6XPlnwdF0fGuQm+Ovv0F8iDFhNnSwxVvn07mDZLtilYT/hmYYFTdhW+gejIz3FSBHKeekFshRiiI3/aJtamXlQzWpz/cUZaMv2tU8s1wrrlumlr/6B,iv:qCgVvZF/c+SQGSHfdamE3MSIKgqZ87zWgPiuj0AlV+E=,tag:Oktm4+hqOs2iJN/0cBILcQ==,type:comment]
    db-password: ENC[AES256_GCM,data:8KvSmL1uqWIEHFMf9jm2D+4cLR8R50ZfeUfQmSmeTDY=,iv:svUkyU5FsYTqu4uacTl0fYCUWF8xxqcK6vBVVa2typM=,tag:K3+qO2yXhC+Vc4ixa3XAlg==,type:str]
    #ENC[AES256_GCM,data:K96STTg5U+OiUs/Kdd6EDgD2qLpEbRJhU6/W3XDZRRo5tB95Ovp2VGY7k99NQoIup1Y0FpXC90DrjNUinaIZISUqZoH4XqpA79QAsic1t8t2,iv:RLKqfri72B1SHgLQ+fq7W2KeUjOYwjx5JKjpx20PI2w=,tag:Fe++honIktjbzcjA7m2/Kg==,type:comment]
    redis-password: ENC[AES256_GCM,data:6lDizy5lM31jyU8clwOYrQIBJU70Oc9HuaZ7Cp+Vt0vAX+TqM92jUkErEmg=,iv:VUUdEgbMlS2UPaPdtwoPNgfRTq/UOrQy0PO48RnndLk=,tag:mOuHUJeAYOCyQxI9EsvICw==,type:str]
    #ENC[AES256_GCM,data:cKJjWMURdjz516SOS9mmrIs97ydfd0qhjNXOvoZzjPy/A997lRnpIvamrlwXqTUN+MWXd8uI/S1aOUJixnag,iv:TSmKkQMb/4/T8MrA4y+MntUtsz2YoymQqvlmU36U+ng=,tag:yl0kSzNyo99rKgFd2cshsg==,type:comment]
    #ENC[AES256_GCM,data:D5t6BYmSKWlBJ/NTO5dSzLpMkNtgT8LTp4eVsLs6Nlgk/vU5,iv:doH3GXx48qCxOz4yEqaOkdVaChWOCgCIUQGkF+VDjbQ=,tag:trSH76Wq7p8k+bpnkfot9A==,type:comment]
    #ENC[AES256_GCM,data:KdQSL87Vo9lk1ZAf1YZoJeRgOsinlVQnPzUgB1L1UX9HN0d8VDPi9MCdeZWprMHN65D0hStKrD/COelnFL9UoQQddKKpPY89/N+66rOnr9wfuA==,iv:liABL+gsIx1mGqhSiHJ4ISqiJsep1BdPMNHl5r6IccU=,tag:diwBGwwyHViFnfErTqX6aQ==,type:comment]
    encryption-key: ENC[AES256_GCM,data:58LKDj32rIHOBznutKr37LNgx96yoWXWn2FKBNNb/b2dszYfkQsw86lxX7kHckE6zNroEAGM/u16h2VnFGG6pQ==,iv:0fRqP35tgCOcQv8OZI8/NZ9jp3Nj4gwJREGicRLmX94=,tag:ZVkO6NMJnFIgeft3pcGhzA==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWmtmS0dBRXVpd25zaENK
            UE14bEFzUnVqTFlCbDdRTlFLSGRsYnAxd1RNCkF5MHYyRlpRTnVKM0xRRmxySnA5
            bFgyZEFGWlZWMEhWdFU1YnpVMVZteUUKLS0tIE5iREh2aXgvNUpZLzJrM1RxZ3hQ
            L1gxNUF5YmNhdnROcGp5dWJUS3Bxc28K8gnVpYKBjlCb/ARKRbwxMDZotoBULrFl
            csWUdoMGqvoYcNxEflGTFRYfAmjdaWGLxYBDE/TxMvRcM7VvOAVqzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T08:39:20Z"
    mac: ENC[AES256_GCM,data:8zOxvMrPcSFDwotFBnMgMBrLqS7JTUWKEaNvN2haeXJYYTkXEi2cMTCsjQoy2EsiUeWS1vPR84oDxxdhv02SRqOvt1igbAWmH2TKZz0sKud55a3S+/iRWya3ydPlmPD5pBPppvtdRey3ZVMNAsJi1LCyQq8oMCegu56JtSO/X1Y=,iv:PWzlHvLOLS9ih7MwAurD6/N0AnKqH/guukd8BsSpU4E=,tag:ym2YUq1oAzHUWZD2WyM6Sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
