apiVersion: ENC[AES256_GCM,data:PC4=,iv:8Zs4tqdQahkKBTNI1asr/RgbTaTudOuPlX3ZT9hjlLc=,tag:jVeQtI0Cz3LBDSvqi/D/Wg==,type:str]
data:
    app-secret: ENC[AES256_GCM,data:Nl8cSaoPtTlHi3f4teCkj+7H4zzyygvT39HZ7GLVQkI4eA1h6XV4lebbmpxvcfrDO7HrJ79TKKyaV352lWXKdqqD/A6ldABtzrMIn5UwjNbiiOVZJX1Eng==,iv:Cibn0+TjOzVSFj+Q+sPSpg5Vb0dkI1X9LgzD/wBmBGo=,tag:fpRX3B+FO9FwMVNfsBOeeA==,type:str]
    database-url: ENC[AES256_GCM,data:4SHe+O8h0T9aXdtqoU5XAFff4QaY4KY9Cmy5KH7850C7pYSq5kc0gJ5WHipfRdjaRdEh8xCwPO9EYRViPkZBQnIKW8mjvLx0A/7rUxD+sv1JBHMscYiQUZvrYTxxyeafxxjALF0JTTZyWBaifdbYjyur3AU=,iv:dkMifKkLU61JIz/C7MHPqOt6Bs/DzYQru+/4GbHpWcM=,tag:x4mt/+LVRKGjEt7o2aoyaw==,type:str]
kind: ENC[AES256_GCM,data:mSWtuElH,iv:UsVY9z2d/kflsukFHzZKRiY5RtKOITmkKI/OPpkvIhU=,tag:Tc28zR42bZM6nFTsitC+hQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O0mWcPih8xWttMFD,iv:6Eset0ZqbvF6yyywc7GEWB1WQhS5PQD4dIFE966JeCs=,tag:t6ezQh99Wbi3ldIyx4lBvA==,type:str]
    namespace: ENC[AES256_GCM,data:cJqA+g==,iv:E4gguntzVq65b2BDVuvVdiB3Kb4yXovyNqiy7S7wwOw=,tag:EU7unHkNT4vNyV4IdZd3oQ==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdzY2OFQ3VkluVzNWeE5V
            OHlxQnJyNnhFcU5oOXRiODNGc0QwT0NFaEVBCmkwY0c1QURoM1lCOFZpNTJQUkxD
            akVndmhaSElOc1NSQ21QenFEdEFKdWsKLS0tIGVOZEU0VFBCYlNpQ0ZyakZ5cHlq
            S3FIemJBUWFSR3cwUGZidk5ENmVVaG8K8UEzkW6OWp0IbHE99C/gTL42j4hC193P
            5ovjPUIZnerZa+NksMGhtrEC0XSRZb1pnf6moxubkzlWtyb4DnLV0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T11:30:02Z"
    mac: ENC[AES256_GCM,data:mKMomSLmGX77gLJPZZtg1IU9B1d07D3qa0fOyYl+XxgWOYTWbhyAhboXTHW97gfMy8S0vVeMUNBvzqSvgs0YdnoL+Fut6EOi/ECpZnA6Qza7ehQeBQ6Wl6vP0of51cp2mba+sgMvhOI8X0UTNuZVONgVOzZlPExkD/2NWvOeRWY=,iv:hi0MBMraojJ7aw4GIGfHDcD/B+IL8lAKVzIRQd0dQxQ=,tag:jcPzI/M5iLq7iAcY8z9JpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
