apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: erpnext-internal
  namespace: apps
spec:
  entryPoints:
    - websecure-int
  routes:
    - match: Host(`erp.local.kagiso.me`)
      kind: Rule
      services:
        - name: erpnext
          port: 8080
