apiVersion: ENC[AES256_GCM,data:foc=,iv:sRgyRP2mOqamRLxbAicMd8BwJUvym6H1iTqRkXFQ6ZI=,tag:x+F0eRiWsZSJirW/9DqCmw==,type:str]
kind: ENC[AES256_GCM,data:Mb6GncT/,iv:PK1kUBP9VrHmg5ZZcAVEJi/1N7/X/bS/aNuGeLJ4iEw=,tag:9XN0QejKLl+7X+40OuP1ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4Wnt/JtZp165jcvOn9Q=,iv:LPYlsY3ItWKnjdA/FTwccnHUPYS3ouUCO59asXvvde0=,tag:btHB940uORha+YJi7uz/yQ==,type:str]
    namespace: ENC[AES256_GCM,data:JqFK8Q==,iv:DxQyvEIdITtHgjg7OxogOncbjk1MxeWxMkXxxoHJQ/s=,tag:o8RZO3qqbeal4mb46jcc4g==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:LL4iCKiar4ZbBfmknXMSPskrzHZRX/k=,iv:K/d10VI0Mw8uhEF+Ie2SlrzsZLZUyChcGFQ3XhmcKQg=,tag:W2zgoRekXq2hNmRQzdj9YA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:qrwO7wNovbrb94bJtz/8Sb7EiAfd,iv:QCSMT6W9CsU/gcHHXaeRhFnUBP9NgujMfn7fyDuXDLE=,tag:EnBCq43yWMQrI0uM19Tf5w==,type:str]
    admin-password: ENC[AES256_GCM,data:EGH1vW0SBbDnrp1BJrNl+UF/RqXVIdgx,iv:Re0DYOb8q64Dzy1Dk8f/MOASViPd2sj94oYLsQVyiuc=,tag:ZZwaVrSh5YckULxSxnQ8pw==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dXlJQ3A3N01UOWV0SUFz
            WUtzeWR0SmVYdlpWL0NhSDVqZlZPOWR1WEF3Ckh6eWRReVRMTHFCTUQ0WDVTN2p1
            WnNyRm1POXkvaU9VdHBwL1FleEF1NXMKLS0tIFhwdmgyU3liMG1yL2ppK1FrckIz
            NGpRWmo1TnBQU3JObEIyNExZUm5seWMK9Zyi+N1WeDUcJjEg7yYAM6sXSPc9jPM6
            U5+tItrnpX4gpKfLJcresNTPAjyA0okQgM/Y2RC2daTT3JaiDEyBUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T20:35:51Z"
    mac: ENC[AES256_GCM,data:Xy2jvIFWi6p1dmcAsES7QixlSfm/xpm0RXLM00wAiM/9BKqj4GCs7c2gEUwHJkYLLrqb6+O8k2qKDjNCvQv4yWrONs5Its1+9EerFoEPD69qAR45OwUsN5lJ9VhnM6Txz4cVLcMW6eGYi3rjiLj9rZp9sAQvLl7GifYkxr8NC6U=,iv:eNCgf1IS8WX9tWTRtsFooslqqo64nIA5TZrxgbseilQ=,tag:ZqVb3A1LlCQeBN5ZvBznDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
