apiVersion: ENC[AES256_GCM,data:foc=,iv:sRgyRP2mOqamRLxbAicMd8BwJUvym6H1iTqRkXFQ6ZI=,tag:x+F0eRiWsZSJirW/9DqCmw==,type:str]
kind: ENC[AES256_GCM,data:Mb6GncT/,iv:PK1kUBP9VrHmg5ZZcAVEJi/1N7/X/bS/aNuGeLJ4iEw=,tag:9XN0QejKLl+7X+40OuP1ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4Wnt/JtZp165jcvOn9Q=,iv:LPYlsY3ItWKnjdA/FTwccnHUPYS3ouUCO59asXvvde0=,tag:btHB940uORha+YJi7uz/yQ==,type:str]
    namespace: ENC[AES256_GCM,data:JqFK8Q==,iv:DxQyvEIdITtHgjg7OxogOncbjk1MxeWxMkXxxoHJQ/s=,tag:o8RZO3qqbeal4mb46jcc4g==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:iIHfPz/FNbHDr2ZSp7M3LsP4KzY0cNoaWocHITzbVx0NWSWbI7lCdiLqNto=,iv:YQrYUdCb/4U8c4nTFtK03bkjOSTkH7+Mg0DlJZaz+Bo=,tag:7MCelpq8EbtTqZig4WOwQg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:WR0+YO7z5YbHIy3rOcjRd5Bf+ttpukkNFI1UpRGXM1lVfPLLb7la/ZmiCRM=,iv:5AJ5mJc9V9jG7irNhail6daogWeUSFnYpublkT7Cf20=,tag:5LYI+UoqovT0M/rDYkDqaA==,type:str]
    admin-password: ENC[AES256_GCM,data:oN6W6MitEsHZjA==,iv:xR4/hNN6SgYkEFMKg+/qdRZjjgKl9+1NhWz9iVRW1hk=,tag:wCU0ZQB6/CoCBhpo3H9VQA==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dXlJQ3A3N01UOWV0SUFz
            WUtzeWR0SmVYdlpWL0NhSDVqZlZPOWR1WEF3Ckh6eWRReVRMTHFCTUQ0WDVTN2p1
            WnNyRm1POXkvaU9VdHBwL1FleEF1NXMKLS0tIFhwdmgyU3liMG1yL2ppK1FrckIz
            NGpRWmo1TnBQU3JObEIyNExZUm5seWMK9Zyi+N1WeDUcJjEg7yYAM6sXSPc9jPM6
            U5+tItrnpX4gpKfLJcresNTPAjyA0okQgM/Y2RC2daTT3JaiDEyBUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T20:41:53Z"
    mac: ENC[AES256_GCM,data:SbDBQAuII7YDbBihpt8OD3KtiL8q/TIDUebA3PpUgwCGjrHoLGVQl/EXhS0CUgXUokUdPI+IuohtDAy7kHevow6N4/m5oDEgL/5KvYbx4QYNOGVuwPwFpeE1oxFye8totGnlAbhRQehkjddoqw1CLl7h1UoiMEIjHQIJ513XrEc=,iv:66HEFDjoQwYfQtqDWJAyWUpVip+ax2I5pIdult4GaKg=,tag:tBx7e+rmzPPbkViTPbN8mQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
