apiVersion: ENC[AES256_GCM,data:xzQ=,iv:ar6T6fk3hZB5KFVdODHvCwq286PNqcpawTK3/tUGUFg=,tag:cYyWDe21P32WMQ9M0Qb0Qw==,type:str]
data:
    discord-alerts-url: ENC[AES256_GCM,data:htQ5CPA53vAK5Qd+fFHwixwkfRDPbqPQAG4BsZYI+6nJk/FZsLZrs8/wGm3kGfwSG+CQmwFXl5h2zkE9ta7RN6oDiCatp8ZNrzbXrubcNnMFU4XPbHTPWmCt+gAyCeCGNXOTm3BRhavwCmeKLtO4Nyp/nybMrrb6rCYgPqCzf1+ZHs6gxvxdpVUe8vQlWq1QNmXgbTMmMN7WQWDyBoJrLNhqIUold0AR+suNmw==,iv:dnfdvNO2DlV0IL2EnP+BhmKeU7th/4KiR+2VTK8pqr8=,tag:1gTzRcSL1NXGQKVWt5GHqQ==,type:str]
    discord-critical-url: ENC[AES256_GCM,data:jwstb72CIFROl8aSE6QfCG8d2WlPamZqgijcsiwNt090ECkjfZBoFMOPf0UIY9d9rVkl1zCOSoN4Vrc5u0uNfaLniK5fB580024mv1Vc+wt1hVH1xJH2i3HoxSzWq9xRy+z193p7JLdjnx23luiX/C2oajGZOcbR/ncJyne7gKhY63PFWP3zDtaTw41YopHxUMDcmfAM4EuqqOdApaysgwXT5MS7K22rqN050Q==,iv:zb6I/GINCSCqjJWY6J6NEyC+vwl2RHduWtd78oCQ9h0=,tag:fTqpMhqPRWxf4W9Lklya/Q==,type:str]
    watchdog-webhook-url: ENC[AES256_GCM,data:XIL/Wa85YNUJmY7NT3iMtUaLZoEPeosiLJPc1y15/4ESnQ+0VkflsCybhQYKs5xhcDo5P4QhfI+2WvfQwbS4XB5bdRSgEU5UQxUTtzR0QR5gmZ364OC4uijTAUaTZZryDAQ0hdj6bJGfIzrOWjBYOeJXDXTxtSi2mWy/AyOq5DmU4hKhp2eCJkJTKg6/X5jKec2Vcavu/rCCzP+NcgNUkV6iSaOuVK7GWinX8Q==,iv:FxB7O3VOa+hW+USdirFS7EgFqsV5oap+c/GFIIeVZ1U=,tag:HEGYyKLRtJV4WOfn5OFgRw==,type:str]
kind: ENC[AES256_GCM,data:D7+Gjs8Q,iv:sILYlWRIAq1H7wQbR/vP2GoEDCoh47PSnGiPvZRY4J0=,tag:gRb5aLeIRD0F0vQvKsL7KA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JMw0hLcbAWmXg3evTTpkQH9QQA==,iv:8cg1yVdtE0tLBdRkuLpQ9jq8IF+bwsQQiyr3cVW2CFw=,tag:3hCdvNNUA0rAnWoldbbk2w==,type:str]
    namespace: ENC[AES256_GCM,data:4mdmZ1er+vY6dg==,iv:50GevLajNNqqr49vIo/bJtrv9PeOZBaSjZGXUVLPg7w=,tag:Z6kzvC4GGruwGobftHd8AQ==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTamhjT25rb3UzMmU5VVFh
            Y3VxSVltSi95cVRMQUJoQVNOS2tFckRsR1FzClBOSE5nQkVwUSs3NFFjdG1KYXZK
            VWNKWUduTWcxbS8yMjFKZnlZM0hHS2cKLS0tIHgxY3ViNGJwcnoxKzJrSTFmYlRk
            UnBlR1RPZDNHdEZlSE1TNEZ4VG5YZFUKmU+3U8fNjQ5eW0VQAK36t4IaOfYkCmDc
            hEdHUYbdtaaoKNtvwBQQNhwwUZaDDwPAnSmxZpO+mxneKfTf3TBIkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:22:55Z"
    mac: ENC[AES256_GCM,data:aUV5e2jYCXyGb3s5B6XQBlCfCJxYCiXeGs4l6y55UQ0Oj7A4R43H1WjHxy7ffMloLbcavluTCWfacG21ZoPK4zscR6QLZ5oYkV/cpgn3Q75P4R9AjJZ6UsxO18OP1wPDVTRXuI308kitsc9WIlkfa9kHeFzBaQdy34FOrd0Aq5o=,iv:ZEXiUasHMVyq3CwFuG1UP9sjM3ORVwWTI+4r4y7tD6w=,tag:e9U6ad8PwbDbIyhi1d3HKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
