apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-internal
  namespace: monitoring
spec:
  entryPoints:
    - websecure-int
  routes:
    - match: Host(`prometheus.local.kagiso.me`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-prometheus
          port: 9090
  tls:
    secretName: wildcard-kagiso-me-tls
