apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-config.yaml
  - alertmanager-secret.yaml
  - prometheus-rules.yaml
  - grafana-dashboard-backup-overview.yaml
  - grafana-dashboard-postgresql.yaml
  - grafana-dashboard-redis.yaml
  - grafana-dashboard-authentik.yaml
  - prometheus-rules-apps.yaml
