apiVersion: ENC[AES256_GCM,data:zl8=,iv:WGHWib83cf2dePxfUDcvnPHp2NUalgFbYq7e7GmY75g=,tag:MAn+TXOR+9EpabjVifbCJg==,type:str]
data:
    redis-password: ENC[AES256_GCM,data:f+oYBTXj5hRG6yKnhYN04aRaUR3gAFpnFGh2/H8eCjIITBl3C3JK4voxM1A=,iv:XM9nrpyM7t/b8c2EoB/2zexIdpQ+EgEW4rjl63oOyQ0=,tag:VKZJVg5lP7Xb16+HsMQ8Dw==,type:str]
kind: ENC[AES256_GCM,data:vLsFLm5Y,iv:iolp4/1t6HN+DguSsGuWmRlTlZsSr7HXDzlMiVAnKwI=,tag:KP/1tqFhz57/7CILsc0rOw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BSO6TWJkAljIn0xF,iv:tNYGaGzcp4FnmWlkXEQlOBKQEHVdULtcVYKpywG9wWc=,tag:uzVEm01mjbdI4VV813/riA==,type:str]
    namespace: ENC[AES256_GCM,data:mFxovHR/9a7Y,iv:So3rIQ5SRE0CeiJ7xgMGLi0C2m7GQR9gGVT/P8dVxDo=,tag:Hh8YAo4sD5Y0NG3rBCaKKA==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRb0lER3JBeXVwL3h3ZlpZ
            QUxNeldEMTNRMU5NemY2K2dEd1hYbDl2aFN3CmkveUtFb2xlWnFlNWkwQU1mb093
            SjdENWtkUUFPWXh3T1lXckZrMEJ3TXcKLS0tIGYvaDVKd2hWL0JVZXNtYjRnVXVG
            ZlZGMGs3clRxM0xJZUtzN294NzFiMXMKHAOwuP6+TFO8sJDlvc2NIkMt0WV4Qena
            Bf6KZ63PVmbnUbWvPX0caI26g0XZnP4DC9LOjReDnpzpjv2Bx7h8Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T17:08:26Z"
    mac: ENC[AES256_GCM,data:JV5ajjoneaNZS1+vTpi/KfZt2I6M2DxPOV0Pb9HzSL999FwZpKlGsdb56IXZCcJ2K3yA8ZvCterIFQMi+6VavfeZCK/A0rDEFS0OM6t4Q1sqWOsCohqrakSz/ZmyvAAb1xYLB26GYl+MwvJzvA2FtAm9aNV7xA8ZX3dtv3FNBSU=,iv:JltDZWgEaE8/gvGU5RH7hjTNWVjbpGVVQv6cqa57vCs=,tag:IPBALD+ELMNPh5a2Zy4JEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
