apiVersion: ENC[AES256_GCM,data:xO0=,iv:fDmvvOmL6gVWbPGnBlMf7/XdPGtFLfnWdGtC3r50nwk=,tag:x0L+sBthjX0FtOm38CZX6Q==,type:str]
data:
    redis-password: ENC[AES256_GCM,data:vCvkdOc50s417Lac0aY2535XSZV6tQX92oE7cy+sfWo6Jzpm3wEU/7HAVP4ZsQA2Unt2xweczj1hPt/N,iv:EPbjPl8TX/nDlKTKlQQl3niZB2qplBOaQD4ShbKfyg8=,tag:3NPnBrkku2uHmL3HOaDr+g==,type:str]
kind: ENC[AES256_GCM,data:MK3LP8nN,iv:TPfn2fnUVeFjFM9Eiwz9hvLVs9B/4DVVARqt7CgSd/Q=,tag:4EE4O4pzXk6YwKQB5HOrIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NHAkIPX5tpdbJI2B,iv:Zr1j3PE7w8tLbw56SG7FaS0Vh0AJj0J6Xlv3jNvmmyk=,tag:2udeZTvF1TLrXP44bCxwzg==,type:str]
    namespace: ENC[AES256_GCM,data:qBDYe3wxLtaa,iv:vl89R69JqS+BicKk6GilCZ0yrgyoJL9HoXO+CUnXOEY=,tag:fZn9SyKEpW90c5FJrvJzOg==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ0FiL0huOEZ5RUp2RkM5
            QTRoYkF0bVNJNm5ZM291NkIxQjJPaHk2U0hnClpNelJYZlVCa2tpeS9IR2JFNGRo
            Zmd5SkhXODhtS1dFVHhYemNrTjRkbmcKLS0tIDJCZXcybjFDM0taSDAvdlhUNmNr
            NUpRNE1VWEdQMjJNc2RkUHZSL3pJTGsKjJbrROU2VTzlhcj9j9g87KcGNGS4RjHG
            QSSGtwGQK/JiRMdPdOzVSOwLeEB9gLLrdYAgpWvfh+okfJJSQxO2ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T21:59:18Z"
    mac: ENC[AES256_GCM,data:r8G5eDtqeU2Pn/odAbqvS4EMoqed0JuBOm2eMEv3G2AVPQv+3dsTEK8ZQ7XR9MOe8rsavQhjyH63SkacYCjt9WwaZ591YvsC3q9KEhM5YITe8ERZryRo3f7XUJFH3A7nTmL2m/mzB9fPzbLMADWTGdRnFAGyTnE8JaxiFUCfxpE=,iv:rumXVGpbOb7d2EBXVZJjFhXA/VsEEuaat7JQ9uU/TqM=,tag:Wjp6cyrkQtIeiRxEETrcjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
