apiVersion: ENC[AES256_GCM,data:nUE=,iv:t4d8Ci+yLBaizuojwm2Zgw7ighgckSmB2Z9rAbyF4Q0=,tag:ToBfwxD2ZUhBrioLxmGOoA==,type:str]
kind: ENC[AES256_GCM,data:i1sh3/It,iv:BRDIW9zp9hdcb3v/UiBmD3ecvCPWZ8y+K2smAo79PNU=,tag:5Bm6dKp18iC7wrTgyqJE6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MoLvnJoi5D9Naa0H5+s5puWmih2cUEpD,iv:ZIHyermpEkR8p7RK8GYSO7b99AV20yPM7SFBiJ0wLfY=,tag:iI13ftm4QDv8AfVdDmJNmQ==,type:str]
    namespace: ENC[AES256_GCM,data:Av9tNOC1,iv:eLFaCg3M/mOplIC/JCv2hhJn+LPZTRlzLEN5iTJeyOM=,tag:aI2rWuONzMBL3QSdnO3XUA==,type:str]
type: ENC[AES256_GCM,data:9tHN+hWt,iv:Dn7BLSDvCNp623WbJAnMt1jL9TbUoocwW4ndAq84rLY=,tag:ubaJi+PnpN/Hf8WrOPvfNw==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:rtTNWVj6yizmmNP+2epwMZCgqtxM3ZBNSpwE2cL1lILiGrC5uJCLPgjrJO9PjOpJ774+8zyzo7W8UmqmiTiaJzTn/zCdQlNGWRZWsiZ7y6+QYrKagj8v7VN1f9ZyGazN5hkxd+3IDzqZ50xDLuoeAg==,iv:tbdz4rBvWOvk0fe9Vuy9WoG05xE9zUxWNfT2tmr4B78=,tag:SzCyx+xtim6HEWfyqZpLWQ==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RUVDSmd1MG5QcjM2anNX
            ejlwUGlIUHZldXRRd3o0d001bDFjdElOOEdrClVkbjAweElhT1pqbndFMEhlL0hJ
            d0hGb0MvT0JsdHZMY2NCb2dFNHhmU1EKLS0tIGs0RWhkc0FjWUhVN0NNa3dFNU5s
            TGVVT2JmdjhEMll5VkVUM09XOE82Z0UKGxQvkL5ARLHqp89CcL8YbDgo434rY6mr
            yJhvx/eS+JTxY5pH2PRuV7GcEwQHluQNHpjmCMOMolH+8yfFMC/EDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T18:40:14Z"
    mac: ENC[AES256_GCM,data:/RXxvgeZWH8aJJk4kz5iI4dZiRr1+NZhzHDK+OZP9nmV8sCCRsKKprI45Cxv8Z3CF7NDDmwIuOmAsHV/wKscJQAjrNSctRoIGg+z+cnGIpKP0QJnk2B6KsVPKib3XXzZ5MFTiaBqj3gUWsEF8WscPX+mcPp2qjaarFsLumRzbME=,iv:/Na7xBTMZiL+BDh+XsvhG9+cYPdzT8v+PxKLd3mh+V0=,tag:dV8+6Xt4OBcvk6ltlnCv/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
