apiVersion: ENC[AES256_GCM,data:OXE=,iv:xGqmPLXWktBI5S1ksaCcT2Qwo1JGbicm+3fk7SCSiDk=,tag:uknIlWWxFEhWg2Ym9utbfg==,type:str]
kind: ENC[AES256_GCM,data:1z/mXHb6,iv:70bwPZjHxCirwVhwk97U8bV0JzgBeR+/XoTQZqG8OQY=,tag:FjI9qZouKVHe0ne4LkTCxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mu5s5DaoIiXfVzsmDBDrhK6aLHyJTby8,iv:/jySmu7XBg3i9K2xX9Il4PkdxYe+yNCNqy/NEuCS8Qo=,tag:WLaQ9r2mjfyE1wXoNQefLw==,type:str]
    namespace: ENC[AES256_GCM,data:Av0GeUzr,iv:+uMSwabrZEUGLO9r2vJtDgfZpxsITYNyUmCKzNlSEnE=,tag:VeJVzPAVtcdXjCaowTd+2A==,type:str]
type: ENC[AES256_GCM,data:YTb47yDH,iv:VWrvj1/b+eTkzb9iYO7acwrDy0MUpui1Di3ZpMkYevE=,tag:TIIySzI1D7yYzVDhoJQNGw==,type:str]
stringData:
    cloud: ENC[AES256_GCM,data:OS+o9lDxK/PjMA522ajcpc3QspTc9B9FVupF6pCMEYSmUkz6drD4u9oU6u9jGMqqbxejw8Q+oGbMcR4ClD7iOmNt45Qqb7z8LorwZeocrNs2WywTpTVDL12fQNyGVm1nadfbF2Z7ixbV6P5Mbig4lA==,iv:EF40+UzgpYCcOX1yXRZ4GzPmH+IbLePtbKCjnRfQzVA=,tag:KsakSBOa4SQXGaKnEhBC2A==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbGxWTjQwYzBUdTgyQ3NB
            NlluVUt5V3hCMG1oZWt3K09rK015VkFrdFJrCjlXN1ZIQkFobnR1QkFlM3gyVElB
            dDVOazJqZVhqVFBYS2hQUEUvSDErNm8KLS0tIHFoa1RFTjB5WVE0cDVnUGEzbS9v
            TWgzVWNyRkhUU2ZZdFV1Y1VJSVhrYjAKPW169EL8qGdOBcP2pbR7iTK+vy3BUIjT
            I8zMnRXqaYiUzPULXHHzC5fjxxoKm1QtuJ662EhoejJJ+wPGyDhiRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T18:43:09Z"
    mac: ENC[AES256_GCM,data:RJd+4vb4G+Ixr9dpdFLC1nBKLXI2+vhUHXvIoctF1x9XlJ7hkTdjN2SaKsSd/Pq3Gi7Llk53S2X/Y+0ZW1hAMqaBDksBJsJqfaY6zl8A1dqSkuDwJ9iY5IwpshR2gpw2y1OxlkYvt0wx+RkL9XGqxoAQDqU+bbJJKGXkHiyMew4=,iv:6w3mxBg+t2I2I2NvDrCXuG8yTa2G/hCv9btI3J4Loo8=,tag:9vbrrrI2nxbGhsXLNvs85Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
