apiVersion: ENC[AES256_GCM,data:KEY=,iv:64MHn8pFe9G4ziqwwAey/tYpamDEEN0otptor70RbtI=,tag:O4wDNGOQKNHdx/zmmwSVBw==,type:str]
data:
    cloud: ENC[AES256_GCM,data:ploD0Fu0Xc8c7rOcsrHDGag78oXwhFp1oJdUZylkT2GH0oFqz7TE9M6Cj54WyJe0rdpHAskdAPkjjva0DsB1ARtVlLJBk46fzJkXce/hVAwqNfbEfp9h25n1BG0MqbgSHiZ15ZcljsfSC8cZ72ZMpNiniDuHQ5VnZFeqrluy+HPXvPOc2/YD9PDxEXDAeLqZbtGneA==,iv:uZwVLg/7lPl4bwMR2LOkhdRDRoG7XvXG9sHtV7lRIBc=,tag:gw/BDc0/qkQSVaFG3Fep8g==,type:str]
kind: ENC[AES256_GCM,data:g2Olk/9w,iv:HFWCtP9nMfzTpIhXIsOXXTVFRbcW0GZEu9rJ7YKRUPQ=,tag:W6T9WKXDMpUw9tdRQTIk3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wjl70zfIVo6BE9fMeSbrTP/x+U8jo8R3,iv:9QUOyAB/g2gG3ieoqZBY2gttpno9umyVpL/E4PZEaYU=,tag:r/zRq3UJVdfbe82PfAc4GQ==,type:str]
    namespace: ENC[AES256_GCM,data:ypBOW6ag,iv:xzKLejlqP/Rwi0CCCO/YN3VD5J2wDKfYswGz4mOjja0=,tag:e/+t9uGhog6oYTgCN+LLgw==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubncyVjczTDJGUXVBZ0dm
            ckNETG5lMjhFam85Y25KWXE0V0hzSE9qYW40CjlKN20raVFNQW43Y2s4R1QvUnpF
            QkxRZEZVSnRLVTZLSGZJUERweE55NmsKLS0tIC9TVWtVY0lpMU43d1NGNGtpR2JY
            TU9BaG5mQ1BybEVyMStwalRvUTg2bDAK+PILkDZDkgFxkI/bsJu8F3WbfsxTf9tb
            E59dDkSuf72dDI1NMSYauxRW63qgUyNGp9tlEtTD1e4ioFedc1EGEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T15:58:35Z"
    mac: ENC[AES256_GCM,data:BK8p4yfJMdFLyirM7N1yKdDxtEiKDqhx9JMtHP3sQvGzhe4/ck9/LMfyvF1/56Hmgl1KvVmWMrSy9E8gjAAsOt0dNvCrsSR6yR3CPAeljFo8/QIUOzk8jv3oNXDUazf4yK+ziZf65mVDvzPDzx2dgHKkaViR1YmDxaCDimbdTS4=,iv:kZF+fSJ9uCnbTdjO7XMbP0+9itFLmwOTwfNvsTicDXg=,tag:gRQCABfXIXRRuLXxIvJ2eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
