apiVersion: ENC[AES256_GCM,data:u5Q=,iv:a1bLl1+NJT//aBV9piBqDxsYfiDEWcnAOhB/JEMq2eQ=,tag:cZsGZXaDQDwmujwmgkukdw==,type:str]
data:
    discord-digest-url: ENC[AES256_GCM,data:+gKiSTk0hqYgwI0neEENCzqc2on7VUGE/fWcUzhxj1hjHrwhsg2rOggFP0wwBJsC+kNHZrTzmutZb2V2eize0TlMw+lb/8hulNXhD+QZKSJItCu2V8TEEVdJd4EKKeA65F++J1WFuBPVLcxykmgvKksTKaliE7GIuiXoV7qxQN9sjjpvdj7ZwdNyN+Dk8Xn9tukknBiyz6QBR9tFCyNRhhVvUhA=,iv:gFa1yvYtAOkoi93Py6ln71vT7/40uujZgWggSMBpZdw=,tag:c3WXf9uvsCf5jvyg4UvPdA==,type:str]
kind: ENC[AES256_GCM,data:h2vYN/9L,iv:6X8xemVCuCV25yAs0bI/gd4qKRSW+l0PmLbOlNLWWpM=,tag:5nVIIS029aGwjxfbtLoF/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bow56KQY1tFlzaIeEA==,iv:hscTSNzbCmsQUn5PvIJTvF+M/ubW/GaAXk+PWlWKh/Q=,tag:DYxe1CDVDe8bzBfBmw36sw==,type:str]
    namespace: ENC[AES256_GCM,data:WK4x7rKjWglzjg==,iv:zv5wgWjUEyxwXPJxT7nt8joULHC9PBeMpwsWW38Llj0=,tag:BI8I2FUXUIzn4rFUSCbtKw==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUlkrVTRqa1dkRVYwL2d1
            OUpFeEtvU2N3Y3R0QnM5SlRTbHZmTVp2clVRCjV3RkE2LzNjd3VTZkFBbS9WcUZU
            eDFNU1dHRGhwRWhsVmlXdk9PT3FMQmMKLS0tIGFSZjlHaGoxYmlCWEJGb3J6dXJ6
            WWxqeEwvbndHaFZvSGxjMW9RemtaQ0kKkA/k8VZuwZu4Ph0eulB+B6NQZ/aM/IlX
            y1uA7qVYRvq2q6xu8VcQxR1jL+F4na0FtnNRic9vqxKg8gQjGSWotA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T17:24:16Z"
    mac: ENC[AES256_GCM,data:I87drpw1bZczRhbFXT8EyTXMaVzAiNmtKE4zWCD6FYl1fqr8OI+jIzKO9pKU8PAj+cnNkhG71SPkX0xSpKMqvR5En6qlWVhg2g/c1rqJtd/1ymIb5mfion5et7uYwaVQpYNE1GPpeuwnxyUa6SY7axNJTuXAZIYmwA4K6kiwLOM=,iv:23VXBhofmirPtgYQ9PjDUtQltV7litRz6Mqy31OR9fw=,tag:ZfObYqSzuYHLDOD1BETPlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
