#ENC[AES256_GCM,data:bfaKBiCMj+4vZjm09TTccAXfcafh+Rt831CFG5yiKJTqTw==,iv:Ej/3Nad633NBfGyantqbQCgUD9J1ik58O+X0ShlQteI=,tag:OkF0L/k6fcNcICIcrC4Klw==,type:comment]
#ENC[AES256_GCM,data:1qyWdGeTuMO94/0+VCxh+rS0rbn0v13gVhLUAac9aB4iHmbwPWJwZJMuVsTbD0kbNbYMOA==,iv:TlMVcRFtFImJ5WM/AccQQZgIJQdRw6eOVsGp5XeK/b8=,tag:ooaZbuN9za51SSRtD3TYSQ==,type:comment]
#ENC[AES256_GCM,data:jvlXKKj/XYddQf5Pa03refZM+EnjufiFiKeMWcP0w8xdEajrOjQ7nUf3FJrLG3jZVrJCynLnaUdLLgYGKCO4Njo+rtMUEeRA0o/zNVJLszGPWzc=,iv:+8L+o8X2hYKoDc22P3PX8K8RZOkm9/p/AZAuyaBr/LM=,tag:YVZPgzALVCzK2BHxkssV7g==,type:comment]
#
#ENC[AES256_GCM,data:viy8IRndLgdB91Ij6OfLc5FMGv7rruq4,iv:gpXKJTU4L4UuFvW0pdY4Vx4TyqpA/D/+dEnTyydgvys=,tag:6teDQKGs1FWHCHtWPI7OqQ==,type:comment]
#ENC[AES256_GCM,data:VrkDcg1oFURxz4CW43mOmY+jARxCBaRoMRa+uZjpaNqqEqKB1R401r3m9uiom+OUA74Mg5d3l0sINuhG6w==,iv:ZQLQemnrXnZGWVjPIqy5nnR527r+KRXyq2KTGt2pSMY=,tag:iFgm/9pkkwjhSGsrcqp3PA==,type:comment]
#ENC[AES256_GCM,data:Jvgnf7QOX5Z6zouQ7aZFllg3zb13ovqnYI95I6axF9U/+WJubeBR/NksFtEVAIGp/0Ms4mfyCxuz6UvwXTDmmS64LH4Pmg==,iv:R1wjX9Jt700TPq5JuupBBGL5SjbD1cJCZDSI9mUtb7c=,tag:HYl3BLObo3FKBFoTaMWYEQ==,type:comment]
#ENC[AES256_GCM,data:wsv/tckuM3zh58PrMkHv8dc+lmX5SmHsvyME+E/h/1tXIE9Wj+MHQAVQ0JW390GteA==,iv:e8ZklHFhIFMQk/WnW3hJKDbeQOciCe4SkQIlR/PfFIY=,tag:4T8c6AcvSBGL+C1BTMUW+A==,type:comment]
#ENC[AES256_GCM,data:EVhxmeD4xwancXf1872TnUfeiEMUmcgQO94fWYZXR420b4DRH/7bb4KlbF2vqblHRrgZ+JbsBlkQqS+Wl142wcPzrZJiqESdoJkA6gBT0Zo8xTkGtA==,iv:3fmG7SiWawG3DFrPKLeyApffF347A75UDF1w2XlfKeg=,tag:MM2euSTpTDz7uh5VBMmtwA==,type:comment]
apiVersion: ENC[AES256_GCM,data:qlA=,iv:UNQAqdTYi+R18XdJBqbdR6uYj/JY0sllYbLzal01+wg=,tag:1/S1qVoYMZUfXLJZ9tiPdg==,type:str]
kind: ENC[AES256_GCM,data:lshd/Wjt,iv:mJ5u+ctWltjmhOq1lO+LhP2F0FlKtTzeFe+Bcjvwxs0=,tag:p3ZIV5R0vD5c3FGFCQvltA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mbZY7xRiBZTmQgRZEg==,iv:Y7ytIezBmiqA24CMJg78G4f7dPPGnsJpRVZfdqKHWM4=,tag:paFGc66XjRLrOodIyOvsPg==,type:str]
    namespace: ENC[AES256_GCM,data:X+ctJlawqHHp2w==,iv:4yzvRN6BBwLHipCmbSLhvNyHy9XfA6yIJf7+A8E6EG8=,tag:c1B1wS0ubFAAmQaC4l1O/w==,type:str]
type: ENC[AES256_GCM,data:BvBJr9Aa,iv:7zTgELECZ9c73lVgfXe2oPOsLsXiO/k0XFAbMYIdY2Y=,tag:XX5MiSv59eptDkAI57mO+w==,type:str]
stringData:
    discord-digest-url: ENC[AES256_GCM,data:TcxAIx3UxmchmR4TlnbEknAO6lHjKoOkR6F0CDI3+eUhXmajxcvHp2lqONw6TrBW7wAG/HlYrGj1tl4IHbmQzWoKhsaSB/+4PQ/8TwgbPoUftMFpGpwEUxOOMEps6A22U2UBKFqTAcH0DVcvjHsAHUT0Ybc1rY0vzg==,iv:0qTj6naqqQczTTo10EcKKvCH5jSgOe33A7i9e+BiphM=,tag:V18dUog22HrmJuaf5epWeg==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFoyVnJzWTgxcnJHRmk3
            MjU1amlsREtqNURicjVoUjZPaHdUK2N3RVRJCi9jL3F1RlpGWVRPZlEzWWVIWGVq
            TFJOMnJRclRvMWFyUGNDRjVkYko0NnMKLS0tIFl2bVRZMTZvZklhWmo4QmV6cDZX
            bHMyUi9CK2FkZTRPaHlzelZIaG1YV3cKEZKKUspzqQMpjujdjLyRkHHhhTrpufLe
            B6jFyax9fWYKH+ij8rgfRDu5VzQ3NmSYrl/30pAo8Aw2GS4+7hJk2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T21:33:01Z"
    mac: ENC[AES256_GCM,data:ZF9O4yWWlLc6l1fCSVEA6cANCiXAGZCecpohYAZURgdYgDipBpFAnePxwh90kDAhgjWhCCq/RPfxUkQLWM6hwIRveWYXpEkYd7FWoM3d20tOvMNM5yI5jKNu3K+ruzKjg2Bj4cc3JJ2pEpqO87bOzoSPd9hcyGldEFLfm3yNjyY=,iv:OH3Hgg2LPNcsadeEbH+4CKXRO4Ij3jXkK9hnKYe+AzE=,tag:hoVZLRdgQbQKYPill9AtNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
