apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: miniflux
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rss.kagiso.me`)
      kind: Rule
      middlewares:
        - name: ingress-secure-headers@kubernetescrd
        - name: ingress-compress@kubernetescrd
        - name: ingress-crowdsec-bouncer@kubernetescrd
      services:
        - name: miniflux
          port: 8080
  tls: {}
