apiVersion: ENC[AES256_GCM,data:g/c=,iv:wkzVN3pIBs9ydfsHyyyuy6S4JcTRd9RJrJLbRdk2y7M=,tag:pR6Lty0jBrNYH3pwWbfnQQ==,type:str]
kind: ENC[AES256_GCM,data:BCFEd9Wt,iv:UGtgsFJI98H/ggjU0VzL7yBKWQ17ZF6t2P3sGPzOgx0=,tag:6w8rCYqISZBIl2rjeslbYQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xj4cjH5pDfJgK4RW4XTY,iv:+qyZNkszMGFR3Cp7KGbJunZKmPwvn4Mx1081O7ncSqo=,tag:bMiO8H/YcIb8onN++DRMdg==,type:str]
    namespace: ENC[AES256_GCM,data:wIQDQA==,iv:ApF76GLcSBpwKEkp6SWYE4u0+XT/mE+ddsymP8LR4tM=,tag:b13zK+AwLRuMoaUG6llrCw==,type:str]
type: ENC[AES256_GCM,data:2YpKER3v,iv:AIgUDlP+EOtyF71X0F/XhCsXQ54YqEw3t4TD/Bp7sSs=,tag:Yoel0OzzuUZF+KawpqZ6Bg==,type:str]
stringData:
    database-url: ENC[AES256_GCM,data:6Kxa/e9Q5fQbHPH4zi/n1x8+g9M92LyayztNdBzAniRrf5ueelVkchpM3aZTXIKzku8o1aGxAJIMI6McfHFwjm6t7VAEnIrZmrhxwiJbQqHxNKZ8omDyP3q2mgVczOmOaqkwaVJpqrPxnhLPK3iQwjbf3g==,iv:fsZf9tIJtdmHcmYFN62AAuafGkMq9+eueSl5bC5ZZ+w=,tag:1WazKo7RxuXjHR/WdcuTGA==,type:str]
    admin-password: ENC[AES256_GCM,data:JrfUYz9a7wh3g+HAY/BfrJog+dI=,iv:dIsrRCIIq4VJLdCst2oHiXuBg86550jZd3OK6h6APVs=,tag:6B5hQ+nTqfwdPZtZMERT3A==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bW5JRzh3aDFLeklhTHZX
            TWdTaEZBVVhlR1dCWE9xeStBRlJUQVBkTEV3CmtwNjlzM3ZPdkRZYXVhcHRSZjNm
            RFRUZmRKSjI0N25LWGp4RWpqR01kTzAKLS0tIFpkVjhydjFMa3VsZWVjOFJRT3RM
            Umt0UDViS3dkS2VEbFQzUldhZS8vWW8KNDU9gjDHXHsgtp2Uzafe/vz6egNeun/N
            cBh4OzYuQsZRLNNcyf++6kqxBDAdEeGcvFRmUD61JMAjeNCfySFcKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T23:22:27Z"
    mac: ENC[AES256_GCM,data:fo9RrxUvK6GzI4PN9xUnleSrB7Gekd8gA/dPlBjWe4HMIGrE/GvzXmUxuPafO7JSpXr1z2EPpr65L0w6Sqqmkn57LTLavN7RR2Zk1BGWjqTIl8MQeJ89XVSJBqtRDGSphfUkvgcx7b+y3i36OLcJIFhqvCFmVdimZW3k5h6NHnA=,iv:CYjvc/z9k7nYdzgBEINd6gWpr9yurZKOnwAV33P/3Ys=,tag:lQdH65aa4KYtEgFJR64l0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
