apiVersion: ENC[AES256_GCM,data:6wA=,iv:m9gA3A4HN2kyhe1837q/Rj6gV6OyitsjS6TiOOfcbFQ=,tag:PAwAcz79t301Nb7jAB+Jrw==,type:str]
kind: ENC[AES256_GCM,data:evnA0Pc6,iv:DPb7iVLTDA1NLmeCJFNOn9rPl7lBYG+dZKirhSp/Ljw=,tag:q3+013pBK6SZ9t4JNU6Y9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:guQG59ggxSCT8Sd24dvT,iv:KFmERS4EddCgOlSp0xlhuL6wAyHdRMgOmY362+bzQ4w=,tag:RAQpBCRcCDW0C/Hnbxj7Zw==,type:str]
    namespace: ENC[AES256_GCM,data:en1HcGiBV0M=,iv:firZ+u+UUEklzyrKAhWOjTlRe8PLSJXMpF0yOkE0Iog=,tag:jU79nC6N1Ycwv3h+CgxpjQ==,type:str]
stringData:
    bouncer-api-key: ENC[AES256_GCM,data:gzxQVE3Kvr3bAYYFgTcC6oiNZIrF7OqyDloZd7+/Urno/Xub4+KE3GgGzY5A91dP1nLks9WG5DOz98etGF1Ebg==,iv:HSp+kocyuTVaFmgxNZULGKo7TqdQHESxLOfgYXveSCc=,tag:ZtTkJruQxTTnkPBp8skUng==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vk11MnpGNVQrbEl5T2hl
            OHBHYzZIbStyNnRsMFRINUZOYU8xNWs0NEZrCmZ1eUdQZFloWkt1dzVkZ1dJdFFI
            aUNqWVJtdWg2OU01SFE1eWZ0UDhUcFUKLS0tIFBYUzhaYlZVUXpNY0N2cWFjVTRJ
            MFVvYThwb01rSXV3TnZ5dXNvL2JVeGMKF6+DC3ExTZ3vClEhKe0vWdHXkBp/Hklh
            dBksLnci0afGo0sEWCsWUuSBmaePr7diqwHlgCU1TzvZGuMIuycL9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T19:46:54Z"
    mac: ENC[AES256_GCM,data:jNMIXFkX7sAxF0lQAfHJMjArb5fQmA8/50snv3em+qJqMS1+n6j/LNwY1wk2KWd/L/7MIp+mQVIdprP1OVabOyIR1AaV2Z4PSnQBb4mRTXdsaOVIvNhb2gvkMd5hNiHGP2Ue3cnnH49hS2JyDfdknO0xM1J2pqaXGnCbwGD6Jho=,iv:hlv4GssQjcVxMqlrSdOuYI0kcIbFtOmTMs0ZpDuhSf4=,tag:KnSFOP3tDrzmqzNhNzJ+Ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
