apiVersion: ENC[AES256_GCM,data:zVk=,iv:TPkrPKJFSzGClwOnT0COgWe8FHUuVcY9VzrV8J8wZSo=,tag:+/UyIgHaT2wOZxKyw/fcng==,type:str]
data:
    bouncer-api-key: ENC[AES256_GCM,data:oOfacZJy9nn4S2e7MBplHg==,iv:KXJVymSSukUB/vcWN2rIowTA0oVvW/TSIM1/XqTSfcI=,tag:3hpgENGsej6606heV+lBqA==,type:str]
kind: ENC[AES256_GCM,data:iZiysag9,iv:jtqcSK3MSIXElk/TCRxPkVC23tSupZLaSAbBFxON7K4=,tag:9FeBJHK1CtN9hNygEemrcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NjD4kclWE7B4OGgWmjAj,iv:moVsmMrcSWKINd1WPfah8ubNKV/q+r1Qi9M5Y79i1x4=,tag:lqS3H4tTpoCChRVfIYQTXQ==,type:str]
    namespace: ENC[AES256_GCM,data:F+rqP33Btsg=,iv:ZvfY2bxcTdrcqND2YoEz2k9t7hFs41SFMt2JdveJLhE=,tag:0+nkkxg8yYzb9Q8ast5H6g==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSzRCNk5XUVV6TFB0WlZN
            RTVYYkNBbVJncmMrUVJ2WG1pWVJIbWdWU0dZCndyaFZNbWM1dG9YdzlsUXp4dVpW
            WTNZMWVDQVhtVlhuNHd4L0kzWGl6OUUKLS0tIEUyalNTTnZBNzB0ZHZKWFQ0QXAv
            SVlvbnBWUDZnSkhtOVFjTWpEMTdaekkKwVZ/M2R0oOu/+GI2LV5A3XQCY6gaLruh
            qy0UXAqosaAealQ2bpbEXYy/ICo4G9Tx/9erwxVLeNFGW6ladisBzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T17:25:07Z"
    mac: ENC[AES256_GCM,data:afaI6CTd241+LndQpp9l+cdqYSFPrK4/aALOILa+ipZdo98zmDle+T15TOLxGZpzInUixfALwCPx7Hmc3gSLGK0hEERXZiivPtpOpUS5d5HnAMKB773gw8+2gJJ5ASfRfCy4x+FAa9hmVyAOaTOzBmsUkTNY18Ej8bW8UjexeQg=,iv:DYk+5J3V0yrY6M6c+SrJ3j6DhvUg+qhIairkeUIXRp4=,tag:t01FxfPxNvUSvlEQ99R2aA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
