apiVersion: ENC[AES256_GCM,data:u6k=,iv:/hRbbgDfP6rf64Ip88ePStVSTNA4ZGODd0FOSaZjfCg=,tag:k2/PAYekj11FLbVj+/u4gQ==,type:str]
kind: ENC[AES256_GCM,data:dP0KaM1s,iv:7/hiTQAoX6bZZYuYa8/Rj0uN48CD74e+XkRBrSg6yNs=,tag:LKCUWu/Tq5rl8C5+A0Hlxw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AVISIcWQpXFZx6bRp3eZ,iv:FC0ZqoLOMKQgevQHpJhLVtgomejDmEAWqGUihBFzK5w=,tag:He3dCRS0YQnQchmmCatGTg==,type:str]
    namespace: ENC[AES256_GCM,data:CgU2QjZP3xw=,iv:fyOYnc2VU61Bt/22u3NqGTHi7MMiZ16aCdlcm6To7ks=,tag:DMB2TDKJ4QceFhLTVwJ/Aw==,type:str]
stringData:
    #ENC[AES256_GCM,data:KB1ZEbNgRVkC2ufUDDWnZLJuQ2h+XPXq9NcDsREp8f8PvwuYDhQ7Euc6+BGW/l5LEunWHUnZZVb/VAJO,iv:YjkR+7QOlDjVYIWp8g9vYNS3A51WB4XnMk7gepYrAKk=,tag:i5f4C24cn7reByXR3O722Q==,type:comment]
    #ENC[AES256_GCM,data:DpEu3x62s80yqWeuD5v4Tbrgxm829bj2BikhAiUf4fhyeW7qiIxOSX4L5GnNQZarXegVzxMOsEGR9fBDll0Zm3T81Bd6YodXxw==,iv:5IQrrD/ObbaeiCF8iC3d3yulQsRQAtdPHJ6FCX9Azjc=,tag:Am9nYwql7CQnQJE4Myyp+A==,type:comment]
    #ENC[AES256_GCM,data:hPnXOkMVB5N8ku73ai6u4LaA1NnliV5ZX8D5oYLB1FoGOKse,iv:+JGGn4iSkCGdNmQfhOJK62aqjdsPHRRAulnQyAHG9r0=,tag:hbEQXIWqDqbLxtjJzxoU5Q==,type:comment]
    bouncer-api-key: 12515a548f056a279d8689bf1ed5871bacd399beac6b979a0752939d9e25b838
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3hWakR1KzR0cDlUWXUr
            VWJlZVNGOThwZkVabk4rN3N2RkwwZVUxd2djCmUwYXVxYkVUQ0ZwRjZKczNDWUFw
            VnQ1REtiR0VjdVJ1T2hXaVpURUloRXMKLS0tIEYxSTRoaUlXT3BvNDNYODhUV2hn
            SGZmcmRTN01NT1l5WlJ3QkhMWXN2RGcKDJz5XPxm26NYLK3KLE8RzqOGq9tW7syD
            H3rGjMWfKZZzGA4sDckAhcRTIk6/8sIWpKBY1soC9jf+QjkOxK4QPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T19:39:22Z"
    mac: ENC[AES256_GCM,data:u9Q6pk6Ev+FsUtQBnQQry8LV/TkjhTXmP3gPfSaKAPSMYvMbFtlE2snqIMyDq1fFD6Qbk9NuKs3iWDsqGT/iCA9aAxlD6jrPAyUj13F6ib//k7soyOK0x/J3qJGSO5la+IgQmPsQpmiXNTx1+tDuwfmnB+UOOPGm4PSBqoqM7D0=,iv:5trNzLJtO5OxtNWhfP9d/wQGIxECmFFEX0aLBG1XSHg=,tag:c+rmXI8JnUUu/G5BWDS+uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
