apiVersion: ENC[AES256_GCM,data:SXk=,iv:7aRFCY+oEL+NTLLTDhazkrgiU/RpSak2SeleKl3wK30=,tag:kWY2amyhO1RFZAEZoQvK9g==,type:str]
kind: ENC[AES256_GCM,data:zLIAqZI2,iv:3hCP0x49pqk8h4WWS+aC7jlWhAHLbo5vxY2tfrKckhg=,tag:SIAGWDjmw/RLDUK4pGnLww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M0xucVTPCObnFVvZgigQjQ==,iv:kj/j1gT8bgZlRIUFC7emBcl3JxbRHqTYnA6uNyo1K7U=,tag:IeJcU1S994IOhBnbpFxWPA==,type:str]
    namespace: ENC[AES256_GCM,data:Nph+Nw==,iv:X0vRGaN6bmQfmq19jG1t86mIUnXIFXI6p0Ym1tun7Gk=,tag:1VhPE3mVJxszyaQT9XOm6A==,type:str]
type: ENC[AES256_GCM,data:byinB5em,iv:ke57+Do1AWX10RTugFN04H2+1N3HAXerTaLRBNzMU88=,tag:PK1JoMCgUUVpj0Yf0lcyTA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:insf4xTM76Z/nrz4lILZ+uQ2iQM=,iv:zguI7fVmdEwVp1bJRDBm7rQ393SgjLkr2b3zUGz83h8=,tag:EGnrkyNe7Ma25Gf1cgQk/g==,type:str]
    postgresql-password: ENC[AES256_GCM,data:6GgItnpbIZw7tCyGipNKDAyLQbuf4OQJk4Xd1v1ftiaFYZRJFOdq57E8nTg=,iv:K/WvXMUxRrQiE3Kamz1/SMikJcSFOFx6cdET1ngY0WI=,tag:kBXBTvAZj2zz+d1JgHmZOA==,type:str]
    redis-password: ENC[AES256_GCM,data:OR0sLIJsNNbcXcN9Ef0TY6+eI08CbgjjMr6YlWpBV1JhrX6eZ1FPAaB6bi3wxHZCu5VZQMuTGOMPOTLf,iv:HEJbUBDgx460nVj8GBQFUWh7Kt0w3SaBYveC3BvDGLU=,tag:p/znSszmp6tLZ7pCfRF9bg==,type:str]
    smtp-password: ENC[AES256_GCM,data:F+/r+HUMHjRnFx4JhwfeOPgV5h0/l181CDgG3+LU0EbKF1zI,iv:z3+nUUcPT6zktYEYDuoZt9G4WRD4lgDD0IGndqYAOsg=,tag:/JrebXHI8W6XmFozrstPhA==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UnJoMG8rOXpraDBhMWQw
            Qm90SjN5aTQ4KzNyL2srR1N0TG05SnJsY1VZCnpuSjdab1pKZXkyejc0UHU1RVBp
            RTR4QTVkS2d3YWpLU25TaUx4NUkrRWMKLS0tIEVmd0tyNm5LelJ0aG9PRHYrQnM4
            aEkrY2orTmhXUGlzMkI1a3ZndUViTEEKS0RFK+f1ZAXEEDqjprqQU+J0VHx3s62+
            hA1zgQB/X9nGzJ4y8h6/zoAS7h3iAS+Q+8R4hZ+FJirsCnPfgLWeZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T22:25:48Z"
    mac: ENC[AES256_GCM,data:Fe5z2TLovUFw10MnqZLkbEVLTVM20hiArtrSqkh7VmRIffXCp1Z7MZbQebjz2vyVNk1jelMSC6TU6qZaF/1T1/9IDEBPM1xm4wLhLMOMLbdG58O3K5aqrxmflKocsb02w5/42gOzjliWw3StamqnMMosIJCQ74JM8RMFt3HZusQ=,iv:6L/FV1iXREPeCCxCIWUjszOLP8aiEEMd6zxdQRGPH30=,tag:YiaGDdQiPlVlB8xUjxRIHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
