apiVersion: ENC[AES256_GCM,data:SXk=,iv:7aRFCY+oEL+NTLLTDhazkrgiU/RpSak2SeleKl3wK30=,tag:kWY2amyhO1RFZAEZoQvK9g==,type:str]
kind: ENC[AES256_GCM,data:zLIAqZI2,iv:3hCP0x49pqk8h4WWS+aC7jlWhAHLbo5vxY2tfrKckhg=,tag:SIAGWDjmw/RLDUK4pGnLww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M0xucVTPCObnFVvZgigQjQ==,iv:kj/j1gT8bgZlRIUFC7emBcl3JxbRHqTYnA6uNyo1K7U=,tag:IeJcU1S994IOhBnbpFxWPA==,type:str]
    namespace: ENC[AES256_GCM,data:Nph+Nw==,iv:X0vRGaN6bmQfmq19jG1t86mIUnXIFXI6p0Ym1tun7Gk=,tag:1VhPE3mVJxszyaQT9XOm6A==,type:str]
type: ENC[AES256_GCM,data:byinB5em,iv:ke57+Do1AWX10RTugFN04H2+1N3HAXerTaLRBNzMU88=,tag:PK1JoMCgUUVpj0Yf0lcyTA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:insf4xTM76Z/nrz4lILZ+uQ2iQM=,iv:zguI7fVmdEwVp1bJRDBm7rQ393SgjLkr2b3zUGz83h8=,tag:EGnrkyNe7Ma25Gf1cgQk/g==,type:str]
    postgresql-password: ENC[AES256_GCM,data:6GgItnpbIZw7tCyGipNKDAyLQbuf4OQJk4Xd1v1ftiaFYZRJFOdq57E8nTg=,iv:K/WvXMUxRrQiE3Kamz1/SMikJcSFOFx6cdET1ngY0WI=,tag:kBXBTvAZj2zz+d1JgHmZOA==,type:str]
    redis-password: ENC[AES256_GCM,data:9krMxdRLavf0uRxogAsCmyXqIWkhFPEkP3tuga7C73NKgKUaHgxaWuDPJI4=,iv:fJY9wr8iztWCF7YUx6sDLGGYBYvYTTjNg/Jrlla8m7I=,tag:BzwaiZ/9OM8zaq1wEPJnvQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:F+/r+HUMHjRnFx4JhwfeOPgV5h0/l181CDgG3+LU0EbKF1zI,iv:z3+nUUcPT6zktYEYDuoZt9G4WRD4lgDD0IGndqYAOsg=,tag:/JrebXHI8W6XmFozrstPhA==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:PoMuxdmgueqzx3hOIiwOetN8Ods3ap2UaegpxeDsRAov/jVMQK/UEw==,iv:XCc18RBWs0iGhAMCcoUcbUatWKrbNx6xHeZMFeg0OdY=,tag:pakXvIRg7DvWK4sqvF/y7Q==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:Ympr+jhA3OgzQVwM7zY8VLwUgiZow5G9q8EswTAxZ6jVmvuWBtRh2girXKnG+7BK0vfgt04cv0TrfllVvWsEK+M16h/7/VX8gsYNtvxGj88Qx/7FVIn9r2i3ZTim+sTVph5cK6Jz+ZE3U1A3fnXXXdJkeTwJEM2E5TUBxemPIiw=,iv:DL5gHIRNefl8JiXN3d21UnKjIUepIx4qBPYIMb6fzZU=,tag:rGdFc/XPcFpZCf5G7mNVuw==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UnJoMG8rOXpraDBhMWQw
            Qm90SjN5aTQ4KzNyL2srR1N0TG05SnJsY1VZCnpuSjdab1pKZXkyejc0UHU1RVBp
            RTR4QTVkS2d3YWpLU25TaUx4NUkrRWMKLS0tIEVmd0tyNm5LelJ0aG9PRHYrQnM4
            aEkrY2orTmhXUGlzMkI1a3ZndUViTEEKS0RFK+f1ZAXEEDqjprqQU+J0VHx3s62+
            hA1zgQB/X9nGzJ4y8h6/zoAS7h3iAS+Q+8R4hZ+FJirsCnPfgLWeZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T13:50:06Z"
    mac: ENC[AES256_GCM,data:2ikiAz3XV7OWrbXULi6HzQVSsgwK8svFJpHEKM8ft491OWimj7B6AypOrNia3qXInRZcnVb+NNxzJK9Jb4IqGKT3K6mRubZmJLGIin4huo322VBxYt1EUGMk7wVOLdduFJCU21KmUm+GeOlVxqiCeEc7HPfTMOCRv7AvGNL5ntk=,iv:bQOtF4lFRvdEeQGMvzUWkB+EnaT/kspj4wTPtqJ98Iw=,tag:lDQYdbnh0exrhWllqg9gyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
