apiVersion: ENC[AES256_GCM,data:e30=,iv:baTd0E/lv71CSlaovfntwhK84g+OJ09kpsqYuMi0u7Y=,tag:TdWeixlngsBY0j8p0khnNw==,type:str]
kind: ENC[AES256_GCM,data:WN5BbfVC,iv:OSl7HwLU7CKjel+Va1Bg7p/aQQBWJmaz6800e5jw+tg=,tag:mOvIAyrbck0b2kvZh7GJWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BioCdWYSr7JkTASLjc//wA==,iv:bsGh2uV4NFiC7lzoB8tDaJZ1Yc841cyhfBqTQE6bC8Q=,tag:2+49ZLotBQfDTe/NbyEwKg==,type:str]
    namespace: ENC[AES256_GCM,data:8G155Q==,iv:B1bkDTC7pIj2PxoykMVVigbhR5x9wjIOXsMM2GxCXdM=,tag:trGYQRf+K/uI9/9M0M5FhA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:lJFvgnLfL00AFycfto8LaOJaVJpcFw==,iv:rzxPxa2UKPZNEIC3udKIMtSZwDc9kthFBRrpRA6jeVA=,tag:4Vc8ZSPf98QS2N3Oz9IjJg==,type:str]
    postgresql-password: ENC[AES256_GCM,data:l3MByDQyHJfDzyQ4lPbszKirIr5krMidxRLuMbRPeCA=,iv:jKo4S6sLMNI1AS4ZbgV9WAqOKFUNtLyqEFQLp2ccHdQ=,tag:axsO4Unib1j9isT3svhS8w==,type:str]
    smtp-password: ENC[AES256_GCM,data:lKG26oSdSZxq8A0ZS5sMXyA3yqOR/kSxWbAWFLT8ck8vVM9v,iv:FILDR+oGYfvMa2bt2M3xX1lKN4NrQBRYorFBf3N1ni8=,tag:MdFSc4e3g9dtEbD7I52ppg==,type:str]
    redis-password: ENC[AES256_GCM,data:2dcY0D37vwI5TlJptHaFhaxLiL/SeFeKwi1Eyg42SrM=,iv:6XWOv3ZPC+UdtwEi3e7I0auVTUCVmpQGGc57qK97rts=,tag:PBeN4utfINbK1fGTUS/ozQ==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:NKijPLoAh5VnRkVh3/wrU3Ob0UCHD+JjXxR51MnMeUehwqbD8R70Dg==,iv:PtGJnVQcE20Mp9GN39+Zl3TfNcnU4akGzDxlIySxguQ=,tag:ax54cSiS3bWal84eavUWVA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:4a3mBqgnvGd6khAG9f3OgxAm5yyJ7tUNqyXQauosBFRcAqyddnPu0dduLHC4H57x1W+jx/2hS8RRq3RvxXoJgGa5DXRGMLuXVaFLFo6aM+JCgAZSPuCgXJ8nM9S/YVzu8LjCHKLLZFUOxcQLKV/uGXKXS7YQtddehfu7zAG7BpY=,iv:ik2DszPMzoPtrjK9+9XiobCi7pTBsHV9I4sfN5OHlic=,tag:NDp/Z/txndRmuHifend1Cw==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNFNtYzYwZ05sMmpuQVNy
            bmFuWll0WFhqMzBrYkYrVytKSkEzTHVCaWxZCnBTVXBHTUdBNWdjeFNwZVUyV0w1
            aU9Hd2N3TEo0c0owM2tiN1BhRE93ZmMKLS0tIDgyTFJrYlQvRzNiNWQ3cmhlWEtl
            M25aMWVXd2daNGkwcDZ2SWhTUWkrbkEKiQr2AoAyrFtJ7OSvu0wBmjbwgDpbdZWq
            AseAr0ZcynXnmguQ1aUZxD29gbUKzbZhFMFFccH6JFC8kNFxDkQTXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:28:39Z"
    mac: ENC[AES256_GCM,data:Z7onNl8Z757HfuNCVCCWFRVgU5AiLCCpXkFkyow8lwLJpk/3wIk6Q1nZpgUrQ0wZFmoG/ZqmK/MtB9iKvjMy4lnQlpRsJUBGeWPKPMNoFOmgaq9G2CIrlp8MEtGVHpyoYx3veg6bIZ5sAWAbS5SxoKH1wnupcmrP/PqmasN8hk0=,iv:jkULovXeHGXzxQpIkhCwJYbuDjRfPWvOQpFdbnm+b9Q=,tag:CDI+BoFyUnjWEzCclGwfbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
