apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
  namespace: apps
spec:
  storageClassName: nfs-truenas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
