apiVersion: ENC[AES256_GCM,data:lBY=,iv:xEiW6DIbcOQuyxuhnh4Y3E+LnRCH9lmkeKyiVhUJx48=,tag:XoVUvU4nACas+7StxHtwuA==,type:str]
kind: ENC[AES256_GCM,data:POiGEm3W,iv:JuO57g5laDd0df3FrLRNdXrTZCFeOk16GbAkhXq2K2I=,tag:8CULQj7tLiF77IeFkCDWJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OGdFbBdMR1LFLW5RYA==,iv:bxzRQ9Fs30XCI7uRFOa9uxaCsoce8AvYMtM2CznZ30o=,tag:/3ntaSNprGRDnA1M+FWnqQ==,type:str]
    namespace: ENC[AES256_GCM,data:lCIsyQ==,iv:P1wE6lwxsaD6WIJKu8P9I0fGxPI892iUo8GzhF2v080=,tag:93/FLTVy8/3VALu94MGlQA==,type:str]
type: ENC[AES256_GCM,data:Xj6grFY8,iv:cGFtfZw48F/vYTwOA0/v15lqZZEZCR4xuDuQbORdpJg=,tag:dezh007TO5wOBxO0m4wkoQ==,type:str]
stringData:
    moodle-password: ENC[AES256_GCM,data:HLFhvJqXlayg/6szFLYDt6rGYkjvkrOR,iv:jqmUoI6offY68COdPdldKNB3iIUO9fQBr4p2YQ+wTwY=,tag:+onsP2+gZ/BNYyKwKLwK5w==,type:str]
    postgresql-password: ENC[AES256_GCM,data:+0W4qhBYcfuWcdaQ+NTknLpEJUJpYkI1,iv:Y3uwFj3sAVBtMgY//tuwJgdsZMNjpaweflbNam9vHT4=,tag:Zz38yKkCbm7JQgZvvd+wQA==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJck9WRXdOcEIwYTViRm96
            WFVOVmtyNVhvWU5yYTlyUDMvUEppRm14UlhJCjFWNWlxN3M1WGxnYUtZakx6OGs3
            ZEpUa2RsRVArSUtTWjBNTWRJamNmNEUKLS0tIEJ2RkV5K0QwR01NeEZyVE5LMlpz
            UFNZc0tBR205QmNqUkkzL0FON082QzAKKbfoO6OaW64IeLtpJswMvpfyS+Zv3Pfy
            N9q9gfEx7mb+e30LAGVBKWRpk83YbclvN3L35o4qGZH4yhS7eHS2kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:56:22Z"
    mac: ENC[AES256_GCM,data:eiZmXUmC5Piz4eWL5FW2UqDeZwbWhwXDRr0UxrjlKGOJtgzSfT4dN323Cs7Mo825ZfJMXEXf/8EScnkFrh+sCnHHubK+9cBOlnRkLvKtcEUes/zAWkOOK3BlzPki9CD68SITnhfOGyqyipNkAxso/7LEIOoQcQtm3DabO8llkHg=,iv:ucUAoY0qSDg32kuevfH53LLUSjZ8twO9ZqXATyBADRY=,tag:ZH4X5IqdoX6urkrbXHFsjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
