apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-truenas
  resources:
    requests:
      storage: 5Gi
