- name: Install K3s primary server (cluster-init)
  import_tasks: server.yml
  when: inventory_hostname in groups['k3s_primary']

- name: Install K3s additional server (join)
  import_tasks: server-join.yml
  when: inventory_hostname in groups['k3s_servers']