- name: Install K3s server
  include_tasks: server.yml
  when: inventory_hostname in groups['k3s_controller']

- name: Install K3s agent
  include_tasks: agent.yml
  when: inventory_hostname in groups['k3s_workers']