apiVersion: ENC[AES256_GCM,data:rMg=,iv:al6OLH8pC3AEY1PAFUj+wwUpEmfRIfbuNnb9oHBzaZ4=,tag:dm5CZBF7daVJHnfWO35BEQ==,type:str]
data:
    bootstrap-email: ENC[AES256_GCM,data:GW30Q8G9U6k3Kjy3+PaYcAMC564=,iv:LxN4A4kFOHc3p02ai1XaxGHkzZeqPhWhpzL+gWQb7TY=,tag:6/++YstAJKx//tJkWr2yUQ==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:oIn54FibOEUFh3TieekBGymGjB/DHJZrTXoCGZ7gB6g=,iv:qTBddJF6++0K3MY5hhBEYMgnZ2xQksrS9tB/Tu4pzW8=,tag:7d8VsA08+Cs5S+D1xeJ3FA==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:UaQjhbbeyksak/TQFEFa6hvj2B+vMLLMDgNe3EV6xjVNhKopV3Ts5HsTDEf6lwkMh9eekxJbXZ1L7A09gRedmi0F7L937RquaaN0f5xcWjFZMVI+YCyC5Q==,iv:PEN+59lZ0ouNy4eJxCjvzqOPao7rv/49cEOMH73glcI=,tag:uZCjpOqoO8/0rwIVK6NPzQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:bgG6f5jdx2efSOvDVQ1AxDZHKRxG1lxuxXoeRH9q7pzUXOvil8vSCV+Ylgg=,iv:/peRo3zPxSDJ3G/z2B/yTMPfFLXvUYgNqcUcuR4+5Zs=,tag:am7Kh5FBVomtoMrVGxbIOw==,type:str]
    redis-password: ENC[AES256_GCM,data:0ocPrT/QEfXagoDkzCjhf44HmTVg40fIAGRE4nFV2wm9xj/QtaVd0BvV7uw=,iv:RvBZJdVoyvjcLadacF/qfz8WMUF0e5IYhx0FFhYpAQw=,tag:cvo8nHk3rrTqqDl8SJ8eBQ==,type:str]
    secret_key: ENC[AES256_GCM,data:HSUdnWciHW59gszYfeWJqvlGHW59RjklSPQPO7XuH5o6Y+wUlLE5qr27axJrR040AaNKwBIUjYDX9G5kcAaUgnfhkvJIqVg5BQvZs63SWTKlbWQLGY0iUYK2vyo=,iv:vjSVfrKu6r2VQ/DTeWd1edX0//6v2ple1p9bcYqwI+8=,tag:vVs5nXOZ2y+5u9RdboMCaQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:4gPtYfa+WrK0ckcPKPeyc53b1APmU10agAntRsJxBacYiOuf,iv:rsVxYZLNjwWwdywyyY5npKKN6wxYlEshqnodof7oOeM=,tag:+jtKKSvHb4//758FLwJqnA==,type:str]
kind: ENC[AES256_GCM,data:Xq6G2kbJ,iv:avfipEHF9a3KykCwKcPPh/H2VrgN3pm3eZXEmVAPvFw=,tag:ZY3+Gh/zYa0QTVIsyf5izw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1XoX6v9C3JJ+4GqH6L16qw==,iv:pB81IrKS6yaQnlmMtk99GmClH7fVjj3S7tbaXtdASfM=,tag:RgiqE7w+fLnW4HRHRJbbaQ==,type:str]
    namespace: ENC[AES256_GCM,data:1BUpzQ==,iv:9ln4YGwbEShOLfgx0z5mTdiRvLKMU6QWbTZRX3ZRguQ=,tag:B2QKiSmWmnwGJTCHOBn9hg==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z25qdEl0azNDYk9RMmpP
            cmE0YUVSTEM4VWJTZnhtMUttaC9YTVhmYkU0CmVBUERidW8vZVQ4VE5qZ0JqRjYw
            UHVRSzNYSEx1UE40MkhtdnVXQ1hMKzQKLS0tIE9tcFBGVGtLaGQrQ3hTblI4aEZJ
            dkJmUjg1VDQ5NWtpc1V5Ukx4VS90eGsK0ZqBmKaLSHa4pAxq15G32awcUAtrDzwJ
            Voo0DOBDa1WGMADWRFUepSeO8Cne2v7lMW5dPN/55AYs1DdIKDiigg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T10:42:28Z"
    mac: ENC[AES256_GCM,data:e7BENO76CZ9cSg0BskmCbLMtnDVdPFS28QX0BjYW5tGXbgUzVafCpPYR+ap1+wcY69hQKjV1vegBSJosNdb6JPFI+sGecs61KO/U43X+AmgtErMUjcwE16WxksUdfdc2iRx/2W1xfTuu0YB6d0G4mlXeofw0RX1GX9rugcfFXzc=,iv:2BWbPKaa245Zo8gmAE03z5Pm//CFGhIU7dgI95/D8hc=,tag:Ya262qF7H7m9PuH09tcktA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
