apiVersion: ENC[AES256_GCM,data:WE0=,iv:r/uO3m/wVQsptAXPkUCIBw3fsgOWsYDZkQeZOnNEkzs=,tag:jygSmquhYHdTc0Z35qRONg==,type:str]
data:
    bootstrap-email: ENC[AES256_GCM,data:k6c6Qpk8T4Os2+AJb2S+KrS/0Z8=,iv:j81Mo6WjzAYI8WZgyj6x/a7pEPumA3TdjHqStSvq+CA=,tag:++lUVESS8ul9Vm3n47AMkQ==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:l1qFkuBIbz9RsfgOKYgJE2anYeP58Bke10tLCYovvIg=,iv:LHIdXh6GIlhXPsOyVLMiVxSPU5lrM2pPQZRQ44oXaU4=,tag:HoGxX3PW50fzuqSv5H326A==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:0VW14Q2lbFH6bUt5aDAZp663pfDKbGnEA6G3BTlpK9lR3UDcr3KnMpjV3x9wfNUA9xaKk6EQu5+Wpgev+SM0ZwqVqvcMsPlhbKO1qq5k2RQ23TBPViurEw==,iv:GGU0861ko5GnWCGV2TWyWwe3G+3II38opeGh4OtCM4k=,tag:s5VdUEXxYH2DbokyR1XBCg==,type:str]
    postgresql-password: ENC[AES256_GCM,data:XYsxJ3vgh13G+x6IZYG5EELKT3z/ybCnSf3bKHAOhpjbcNhpLcrgerkQ4zE=,iv:6LcYVWrBdneTvmENiuCMP3PQercJSjk13LNQ5s0T1dg=,tag:n3eU9pkmVlILyTwsYpAalw==,type:str]
    redis-password: ENC[AES256_GCM,data:TeKNN0UQty88c9YYOcXvPiJsd8q9YbxXoPggFwDqb3oBIxP2rBLzCH4fz6M=,iv:np8NTxEZI1AXwhDmN5F5A2VPxrpbo6RVJ3jqbjMObbE=,tag:e4aziEod3TdWeL3PjPEQPw==,type:str]
    secret_key: ENC[AES256_GCM,data:vaAUxZnto7wPK+nnmfhmtKvNhjXocMKs1xEtM4ANrwIaLgyYaDbdLo0kgz4CyG7h01DuwhehTp6iDXZOB2kvPv3dN81RE9cfEujBzqpbfshP8GTMwemgAAktyj4=,iv:Cn4r2LXE5PsuSdU9/IR0ZugsNqjkXG9TH306jMXJHVQ=,tag:LVRftZ0cMXWSgnC9aIAWsQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:j+dK/DYwN9Jel+APw3lJm/Heg5yaPsFhwKW5e2/n5KAxB1R3aOvTTBqOUsnIbd5c,iv:IEGpb3rm1xO9oe5ahz7PEDqaIk2nV9ONZ5L5Du4dM9E=,tag:HgRvb5dbayTTkqs3pJZ/TQ==,type:str]
kind: ENC[AES256_GCM,data:v6Pg3HBH,iv:242rZk+Ke4phVnRYSRpCQ8BO/xUnnC2PmqYAF2nJT9E=,tag:xE7OnroL/3SDBhmyCXnVXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Eac0LG55B4O8HQMATMh7fg==,iv:HarxBnTyCfe85zSU3QGgwSddwVUEyRnmbIHK6hS2XpE=,tag:E/Ij1eRRBywuwc54d8BKhw==,type:str]
    namespace: ENC[AES256_GCM,data:os8Wqw==,iv:1+pxDU63fem1wQsliQU9UdbdOEdGJLxlsL6ckoSfDa8=,tag:fW4Dsf/ImerOBqhnLSVxKA==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVjBTQjEwdDdUeUdibGp4
            UzFLSU9kWTFtdlM4N2JnZXp6QmhGaUNWamgwCjBRYWhsbFNXVjY5TUlPNkxPWDFq
            TzRZN3c4bVVmZzlueVVsNVpxWHlwdmcKLS0tIHk0cE1GSmQxdlBGMU9ZZFMvSnlW
            S3JkeDZnc3JadjZnTVpjSFJjT2JwQk0KPidOsRijid8LB7rHuqQDDv0sFxq5RifX
            skrI1j1zyiQLEaR5/3kVLJLx8V2MFPUHHsoj5P+5Ruq4/lj66aN8kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T20:05:57Z"
    mac: ENC[AES256_GCM,data:7Z6gFoZ7h5XCdNDppLzN+whbHsgnWUB8sdoTn7vsfGhdzHrS1CP8PdL8rxGg1/WsE1HY5wO1zrOb1eiWj4CNRw1CDeAmL5pp2SY5LnwDt074UKuZYT1P5yOsEUtn+oNnPR6/s41dzZu0ugWGE9DuxA2rhWqQBW21PeMi2G0b/bM=,iv:aZ6peW4Jo+4qN6hvYaO3l7+uJ+7ZE4ajzf9NFjOP0Cc=,tag:XCrWxZx3acpBvsln8jMD0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
