apiVersion: ENC[AES256_GCM,data:+Xc=,iv:MeOmEAx7a7pYH+/t0Q3jHadO8e7wbf6IasX5WgZ11QA=,tag:li9RX5QbdYHOxXXV4IU3SA==,type:str]
kind: ENC[AES256_GCM,data:SZK/1Fg2,iv:fj7Pi3daCiL8whpyxPLx/q7sSXw40MJ0spS8clm1U4k=,tag:lFfzFkCDMdqNlGRasWGY8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4S4hSoAp6N6K9Z62kA==,iv:CcCIbd7pc8u3ksOhmqzWptiyfn7E5QAOwyl+5TTljOU=,tag:jY1FwQumZZLiCcGbN6XmpQ==,type:str]
    namespace: ENC[AES256_GCM,data:i2ON0w==,iv:0f4L8WuT/n4cez72SQG4dLYedIYzdTFhduu1RT+g+5Y=,tag:qLB3A5UUsSKRkB9XLdnr3Q==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:2QA1dp65gr2dF77LDIbowg3xIx8CRIY6Xg5vJBR0Hjk=,iv:9aCTLqopRLSlNnbYCiO9mDAceWXRkSbFCZ3XSEK+4Og=,tag:DinIXJBAPT4IPQcqQAWR4Q==,type:str]
    redis-password: ENC[AES256_GCM,data:1uHd+kNRgRDByDViZwOdnjDkc8K0rDp86fbt2MJnaH4=,iv:E92xP4gxyNYQ5V7UQ/W81yI+cD3/lzRuMZaD9+2Hui8=,tag:r3u8R0A1Wv6yGnlkjASs4g==,type:str]
sops:
    age:
        - recipient: age180pmegq0jh7s9ufesme920uda9f3j904pn2xyp452xdg6hx6dc7sxyctxh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMDZxcHZCajVpS2RoNlVK
            elBhY1pFMHI3WThPNjY4VDNjZStaM3BDTTJBClUyQU1ieFczOXJGOUtrSGRJaFlK
            NHhNb1pPYXdTRlg4Z2JaTzRXOG9YNE0KLS0tIGVEK2czbDgyQnQwN1pNZFZGNHBw
            Yy95U3hJbFp4WE5GMm5ZK1g5VjBrTU0KzZIDaA+E/YwMN1Pi1z6lIL5qbjzNaBm3
            H8luWuCK68PKzQ2C/GRtTXxdLfPXPSmz3ArXxZy7ZtbvPHi+f55eMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T22:30:00Z"
    mac: ENC[AES256_GCM,data:C5EK4zKWK6QypWMbSFRBIuP965ki26lYtYafa43bm+EOQNAUGwTMNqOESIO1RRFaPw3huOWu3B7b0eqjFcvTvaES1Br7G708I/LxQglSJz1E7dI7xlPYENpqWVh2KDeXrWACAWFOYLb/fk+Gdr+ejH0ALQnFc0UghzY7kJDnwBs=,iv:b95U4ZymV+AUtu4g5Qy5zt56/z0W0avw/kq5CLc3JbA=,tag:ULqcE4ZoQbvm9x2bUotx4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
