apiVersion: ENC[AES256_GCM,data:HU8=,iv:b9QKT3Kmj35rlJLzKGbTsEKX1fQ7LzZ1WyRw1yxDk/k=,tag:cXUggzNhAT1t/HPepYMopA==,type:str]
kind: ENC[AES256_GCM,data:1peLDM77,iv:ZHlJRvBxY0JXAcAvcbNH2AcoQ99CHa19bpaqimIsi+U=,tag:Dd4kdyxNbLC0kYzMfqD5mQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SNSycFN7JRMSAOXCaQ==,iv:9/tWCeBp2y/ILhvsMkqxT7ZyV5E+O8Qg5aGCWHQg9bg=,tag:JBg5zadDSTw2lC2QpaJ7kg==,type:str]
    namespace: ENC[AES256_GCM,data:pQWlIQ==,iv:KosM4Wrew+HQiDVlogeNNR4mPCK8qdcl1boRiTEai9I=,tag:PsQZvf0NuOqZmZZgw7zG9w==,type:str]
type: ENC[AES256_GCM,data:2Y/98dYL,iv:TmS8FwpoPMbF0ySVMyoIhrsNnWZcEYGDTMPi9Eh+g5I=,tag:IdTjmSxrGPgwvG+z+WZBTg==,type:str]
stringData:
    #ENC[AES256_GCM,data:M1Aymt6bFTZTesz9PTZv+22D94AZQvYxp7jhyNCBx0yAurI3dyyAHdwQZA==,iv:CZWzlD1tqGRHbf7/O/T3Fq61Otw9PCSF5MDOfE1h+l4=,tag:hi7qdmO0mbrfhq9Fs/+Cag==,type:comment]
    #ENC[AES256_GCM,data:NiWh5Dat+h73WqdrLzqHBXFeq7OU4x/jCxa1nopflBYAOqukc5e5BFRKiPh0autz,iv:s1Zi7A+gA1rAJtWQ4o+p5YfTcTFbG9Wq9tllrWllo9Y=,tag:gpGybyFh2bODbPsMDZ+wsg==,type:comment]
    #ENC[AES256_GCM,data:wdbZMyRm8ECAflpw/z21NuAvKaUVWiSA+QKU/hN+l3MFqrULY5fWiyqWtvcaHorygyQwNizMxvsYXtziz4k8DKIE9gDdr/DZFJfUbJzlFoeAW5rGSU4kPSjsRnXAwu6MRh14ctUjxwO2EebX6JXl2GFRuJNlQw==,iv:IAva66uK6Da6a+VwsoTSTWCvY/ii8073zn+oXA1nglg=,tag:MyOB0TPXpQRwxo2P88MikA==,type:comment]
    #ENC[AES256_GCM,data:unZv6ygl6DUJF5zIV22RWz2oh+xDOlMRfjUp5Tgzy0U5u4ndanXgDIm7TZhZhK9iYdm0O7CPBpTL76ShXDcjZ91hktbYMpuoxSkDwAVnpYNo9u2J+nhAoP7a4l8DT44G+KJFDSI/vbTsDyKq,iv:oiEKAT5SVur1syKDg+KQw6ElxEKb7MWJm/DIgs4m4mw=,tag:Cs1eYOKUeMfN0oW1MIfuhw==,type:comment]
    db-password: ENC[AES256_GCM,data:Biqq2za1APOUtXjFA4DnEOLCLzrLxexXNdUMI6qtt58=,iv:QH+NRkaZhJbvbSXlRtZgfuOyhJxig80t9/SzuRZLNAM=,tag:CVeVxB3bPqlxmGuUGSbOUA==,type:str]
    #ENC[AES256_GCM,data:/QgNPvz9cxkDhXlrAfl9MxAsD5GER3hFeZ9WO/FdAIKz5pMkb4SXqmEW3MyuQNiG+nJjC/eXOnN3C/J7ROzmmKCEJ+966r6c6/tb+886esnB,iv:1mQSY9R5RyFESPyHUA+SPA7/2mQmEOnWsI2BtZxqGZE=,tag:+gexr43MmrD5tdM2vI6vdw==,type:comment]
    redis-password: ENC[AES256_GCM,data:Z/1vVqO6qmKDAgjQUSYEr6QMyIqHDaU+0N1yfaI2gwr/ZgeEMF0I3mhdeKg=,iv:HeowhORPortfwXdmKFhcd0flMw4t1Cuzz4Ydai1EA34=,tag:eilqScAbqqHjyUCwzmP0uQ==,type:str]
sops:
    age:
        - recipient: age12c5gj3na6wvwxsmqav9f0x8cg6cycpaas036uy9vyr7jq4uyduhstcvlqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNclliMmNXQW9VM09Kanhy
            Szl1bVBETGJWQ0ZPYmw0Ym93MytIak9HeFRBCjk4eXc3YmpVTWNEczJxNFhoRHV1
            MEozbms4alNHcEJhVXZXaisyQW1KeE0KLS0tIGJTajh1d0QwdUtDWnFBUGJmcTJO
            a2dzdHBHZW5zQ1AreFVtV20vbCtHdUEKCdWZjaaSibT8rMvlzls4ZewA1v8Y6rL+
            O30NYNX9s11SN+Sgv2ameNjtq4iG9a2E8zcI7b5PhcYP3+h6FtbwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T08:39:12Z"
    mac: ENC[AES256_GCM,data:8ZWvz2n7IoNAd7HujyVpn+X2WqealrnWA12ZBQ/X6KnIq3v3ScTlH42dP3W1BH+zjUZmq59xvb7RToU9tZrinyxkUHe8CV2NyM0324jVle3QxWSiwlrFcbwdaRN5JnpNKCAVW2CXULcRzcbJJxQbzMhMdyV22y1YhxlNdYFYNZQ=,iv:at1RYhyOCT8jbE0N+MEzCkUNlnBPTjVEmWnTxyGiJ9Q=,tag:XEbWRbVCzdlPxTzFP57Gig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
